Ikarus::Material
using Ikarus::Material< MaterialImpl >::MaterialImplType = MaterialImpl
Type of material implementation.
constexpr bool Ikarus::Material< MaterialImpl >::isReduced
Static constant for determining if the material has vanishing stress components (is reduced).
Referenced by Ikarus::enlargeIfReduced, Ikarus::hasCorrectSize.
constexpr const MaterialImpl & Ikarus::Material< MaterialImpl >::impl() const
Const accessor to the underlying material (CRTP).
Const reference to the underlying material.
Referenced by Ikarus::Material< MaterialImpl >::name, Ikarus::Material< MaterialImpl >::rebind, Ikarus::Material< MaterialImpl >::storedEnergy.
constexpr MaterialImpl & Ikarus::Material< MaterialImpl >::impl()
Accessor to the underlying material (CRTP).
Reference to the underlying material.
constexpr std::string Ikarus::Material< MaterialImpl >::name() const
Get the name of the implemented material.
Name of the material.
auto Ikarus::Material< MaterialImpl >::storedEnergy(const Eigen::MatrixBase< Derived > &Eraw) const
Return the stored potential energy of the material.
This function return the free Helmholtz energy of the material tag Strain tag indicating which strain tensor components are passed. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Scalar return of stored energy.
auto Ikarus::Material< MaterialImpl >::stresses(const Eigen::MatrixBase< Derived > &Eraw) const
Get the stresses of the material.
tag Strain tag indicating which strain tensor components are passed. voigt Boolean indicating whether to return Voigt-shaped result. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Vectorial or Matrix return of stresses.
auto Ikarus::Material< MaterialImpl >::tangentModuli(const Eigen::MatrixBase< Derived > &Eraw) const
Get the tangentModuli of the material.
tag Strain tag indicating which strain tensor components are passed. voigt Boolean indicating whether to return Voigt-shaped result. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Tangent moduli in Voigt notation or as fourth-order tensor.
auto Ikarus::Material< MaterialImpl >::rebind() const
Rebind material to a different scalar type.
Useful for using automatic differentiation. ScalarTypeOther The scalar type to rebind to. Rebound material.
auto Ikarus::Material< MaterialImpl >::stressesMaybeTransformInputToVoigt(const Eigen::MatrixBase< Derived > &E) const
auto Ikarus::Material< MaterialImpl >::tangentModuliMaybeTransformInputToVoigt(const Eigen::MatrixBase< Derived > &E) const