Ikarus::EnhancedAssumedStrains
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::Traits = PreFE::Traits
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::Requirement = FERequirementsFactory<FESolutions::displacement, FEParameter::loadfactor, Traits::useEigenRef>::type
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::LocalView = typename Traits::LocalView
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::Geometry = typename Traits::Geometry
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::GridView = typename Traits::GridView
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::Pre = EnhancedAssumedStrainsPre
using Ikarus::EnhancedAssumedStrains< PreFE, FE >::SupportedResultTypes = std::tuple<decltype(makeRT<ResultTypes::linearStress>())>
EAS::Impl::EASVariant<Geometry> Ikarus::EnhancedAssumedStrains< PreFE, FE >::easVariant_
Eigen::MatrixXd Ikarus::EnhancedAssumedStrains< PreFE, FE >::L_
Ikarus::EnhancedAssumedStrains< PreFE, FE >::EnhancedAssumedStrains(const Pre &pre)
Constructor for Enhanced Assumed Strains elements.
pre The pre finite element
bool Ikarus::EnhancedAssumedStrains< PreFE, FE >::isDisplacementBased() const
Checks if the element is displacement-based and the EAS is turned off.
True if the element is displacement-based, false otherwise.
Referenced by Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateAtImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateMatrixImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateScalarImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::easApplicabilityCheck.
const auto & Ikarus::EnhancedAssumedStrains< PreFE, FE >::easVariant() const
Gets the variant representing the type of Enhanced Assumed Strains (EAS).
Const reference to the EAS variant.
auto Ikarus::EnhancedAssumedStrains< PreFE, FE >::numberOfEASParameters() const
Gets the number of EAS parameters based on the current EAS type.
Number of EAS parameters.
Referenced by Ikarus::EnhancedAssumedStrains< PreFE, FE >::setEASType.
auto Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateAtImpl(const Requirement &req, const Dune::FieldVector< double, Traits::mydim > &local, Dune::PriorityTag< 2 >) const
Calculates a requested result at a specific local position using the Enhanced Assumed Strains (EAS) method.
This function calculates the results at the specified local coordinates . It takes into account the displacement-based element calculations and, if applicable, incorporates the EAS method for enhanced accuracy. req The result requirements. local The local coordinates at which results are to be calculated. calculated result RT The type representing the requested result.
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::setEASType(int numberOfEASParameters)
Sets the EAS type for 2D elements.
numberOfEASParameters The number of EAS parameters
Referenced by Ikarus::EnhancedAssumedStrains< PreFE, FE >::EnhancedAssumedStrains.
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::bindImpl()
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::easApplicabilityCheck() const
Referenced by Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateMatrixImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateScalarImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateVectorImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::setEASType.
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateMatrixImpl(const Requirement &par, const MatrixAffordance &affordance, typename Traits::template MatrixType<> K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
ScalarType Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateScalarImpl(const Requirement &par, ScalarAffordance affordance, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateVectorImpl(const Requirement &par, VectorAffordance affordance, typename Traits::template VectorType< ScalarType > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
const auto & Ikarus::EnhancedAssumedStrains< PreFE, FE >::underlying() const
auto & Ikarus::EnhancedAssumedStrains< PreFE, FE >::underlying()
void Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateDAndLMatrix(const auto &easFunction, const auto &par, Eigen::Matrix< double, enhancedStrainSize, enhancedStrainSize > &DMat, Eigen::MatrixX< ScalarType > &LMat, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const