Ikarus::FERequirements
using Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::SolutionVectorType = SolutionVectorType_
using Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::SolutionVectorTypeRaw = typename Impl::DeduceRawVectorType<std::remove_cvref_t<SolutionVectorType_> >::Type
using Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::ParameterType = ParameterType_
using Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::ParameterTypeRaw = typename ParameterType_::type
std::map<FESolutions, SolutionVectorType> Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::sols
std::map<FEParameter, ParameterType> Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::parameter
AffordanceCollectionImpl Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::affordances
FERequirements & Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::addAffordance(Affordance &&affordance)
Add an affordance to the requirements.
This function adds the specified affordance to the requirements. Affordance Type of affordance to be added. affordance The affordance to be added. Reference to the updated FERequirements instance.
Referenced by Ikarus::ResultRequirements< FERequirements >::addAffordance.
FERequirements & Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::insertParameter(const FEParameter &key, ParameterTypeRaw &val)
Insert a parameter into the requirements.
This function inserts the specified parameter into the requirements. key The key representing the parameter. val Reference to the raw parameter value. Reference to the updated FERequirements instance.
Referenced by Ikarus::ResultRequirements< FERequirements >::insertParameter.
FERequirements & Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::insertGlobalSolution(const FESolutions &key, SolutionVectorTypeRaw &sol)
Insert a global solution vector into the requirements.
This function inserts the specified global solution vector into the requirements. key The key representing the type of the solution vector. sol Reference to the raw global solution vector. Reference to the updated FERequirements instance.
Referenced by Ikarus::ResultRequirements< FERequirements >::insertGlobalSolution.
const SolutionVectorTypeRaw & Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::getGlobalSolution(const FESolutions &key) const
Get the raw global solution vector for a specific type.
This function retrieves the raw global solution vector for the specified type. key The key representing the type of the solution vector. Const reference to the raw global solution vector. Dune::RangeError if the specified type is not found in the requirements.
Referenced by Ikarus::ResultRequirements< FERequirements >::getGlobalSolution.
const ParameterTypeRaw & Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::getParameter(FEParameter &&key) const
Get the raw parameter value for a specific key.
This function retrieves the raw parameter value for the specified key. key The key representing the parameter. Const reference to the raw parameter value. Dune::RangeError if the specified key is not found in the requirements.
Referenced by Ikarus::ResultRequirements< FERequirements >::getParameter.
bool Ikarus::FERequirements< SolutionVectorType_, ParameterType_ >::hasAffordance(Affordance &&affordance) const
Check if a specific affordance is present in the requirements.
This function checks if the specified affordance is present in the requirements. Affordance Type of affordance to be checked. affordance The affordance to be checked. True if the affordance is present, false otherwise.