Ikarus::ResultRequirements
using Ikarus::ResultRequirements< FErequirements >::ParameterTypeRaw = typename FErequirements::ParameterTypeRaw
using Ikarus::ResultRequirements< FErequirements >::SolutionVectorType = typename FErequirements::SolutionVectorType
using Ikarus::ResultRequirements< FErequirements >::SolutionVectorTypeRaw = typename FErequirements::SolutionVectorTypeRaw
std::set<ResultType> Ikarus::ResultRequirements< FErequirements >::resType
FErequirements Ikarus::ResultRequirements< FErequirements >::reqB
Ikarus::ResultRequirements< FErequirements >::ResultRequirements(FErequirements &&req, std::set< ResultType > &&p_resType)
Constructor with FErequirements and result types.
Constructs a ResultRequirements object with the given FErequirements and set of result types. req Finite element requirements. p_resType Set of result types.
Ikarus::ResultRequirements< FErequirements >::ResultRequirements(const FErequirements &req)
Constructor with only FErequirements.
Constructs a ResultRequirements object with the given FErequirements and an empty set of result types. req Finite element requirements.
Ikarus::ResultRequirements< FErequirements >::ResultRequirements()=default
Default constructor.
Constructs an empty ResultRequirements object.
bool Ikarus::ResultRequirements< FErequirements >::isResultRequested(ResultType &&key) const
Check if a specific result type is requested.
Checks if the specified result type is requested. key The result type to check. True if the result type is requested, false otherwise.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateAt.
ResultRequirements & Ikarus::ResultRequirements< FErequirements >::addAffordance(Affordance &&affordance)
Add an affordance to the finite element requirements.
Adds the specified affordance to the finite element requirements. Affordance Type of affordance to be added. affordance The affordance to be added. Reference to the ResultRequirements object.
ResultRequirements & Ikarus::ResultRequirements< FErequirements >::insertParameter(FEParameter &&key, ParameterTypeRaw &val)
Insert a parameter into the finite element requirements.
Inserts the specified parameter into the finite element requirements. key The parameter key. val The parameter value. Reference to the ResultRequirements object.
ResultRequirements & Ikarus::ResultRequirements< FErequirements >::insertGlobalSolution(FESolutions &&key, SolutionVectorTypeRaw &sol)
Insert a global solution into the finite element requirements.
Inserts the specified global solution into the finite element requirements. key The global solution key. sol The global solution value. Reference to the ResultRequirements object.
ResultRequirements & Ikarus::ResultRequirements< FErequirements >::addResultRequest(ResultTypes &&... keys)
Add one or more result types to the set of requested results.
Adds the specified result types to the set of requested results. ResultTypes Types of results to be added. keys The result types to be added. Reference to the ResultRequirements object.
const SolutionVectorTypeRaw & Ikarus::ResultRequirements< FErequirements >::getGlobalSolution(FESolutions &&key) const
Get the global solution for a specific global solution type.
Retrieves the global solution for the specified global solution type. key The global solution type. Reference to the global solution value.
const ParameterTypeRaw & Ikarus::ResultRequirements< FErequirements >::getParameter(FEParameter &&key) const
Get the value of a specific parameter.
Retrieves the value of the specified parameter. key The parameter key. Reference to the parameter value.
const FErequirements & Ikarus::ResultRequirements< FErequirements >::getFERequirements() const
Get the associated finite element requirements.
Retrieves the associated finite element requirements. Reference to the finite element requirements.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateAt.
auto Ikarus::ResultRequirements< FErequirements >::getRequestedResult() const
Get the requested result type.
Retrieves the requested result type when only a single result type is present in the set of requested results. Reference to the requested result type. Dune::InvalidStateException if the set of requested results does not contain a single result type.