Ikarus::FlatPreBasis
using Ikarus::FlatPreBasis< PreBasis >::type = PreBasis
static type Ikarus::FlatPreBasis< PreBasis >::create(PB const &preBasis)
Try to construct the pre-basis using a gridView.
Referenced by Ikarus::FlatPreBasis< Dune::Functions::CompositePreBasis< IMS, SPB... > >::create, Ikarus::FlatPreBasis< Dune::Functions::PowerPreBasis< IMS, SPB, C > >::create, Ikarus::flatPreBasis.
static PreBasis const & Ikarus::FlatPreBasis< PreBasis >::create(PreBasis const &preBasis)
Do not transform the preBasis if already flat.