Ikarus::ResultTypeMap
using Ikarus::ResultTypeMap< ParameterType >::ResultArray = Eigen::Matrix<ParameterType, Eigen::Dynamic, Eigen::Dynamic, 0, 9, 3>
std::map<ResultType, ResultArray> Ikarus::ResultTypeMap< ParameterType >::results
void Ikarus::ResultTypeMap< ParameterType >::insertOrAssignResult(ResultType &&resultType, const ResultArray &resultArray)
Insert or assign a result to the map.
This function inserts or assigns the specified result array to the map with the given result type. resultType The type of the result to be inserted or assigned. resultArray The result array to be inserted or assigned.
Referenced by Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateAt, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateAt.
ResultArray & Ikarus::ResultTypeMap< ParameterType >::getResult(const ResultType &resultType)
Get the result array for a specific result type.
This function retrieves the result array for the specified result type. resultType The type of the result to be retrieved. Reference to the result array. std::out_of_range if the specified result type is not found in the map.
Referenced by Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateAt, Ikarus::Python::registerElement, Ikarus::Python::registerNonLinearElastic.
auto & Ikarus::ResultTypeMap< ParameterType >::getSingleResult()
Get the result array for a single result type.
This function retrieves the result array when only a single result type is present in the map. Reference to the result array. Dune::RangeError if the map does not contain a single result.
Referenced by Ikarus::ResultFunction< ElementType_, UserFunction >::ncomps, Ikarus::ResultEvaluators::VonMises::operator(), Ikarus::ResultEvaluators::PrincipalStress::operator(), Ikarus::Python::registerElement, Ikarus::Python::registerNonLinearElastic.