ikarus::finite_elements
def ikarus.finite_elements.elementConstructorDecoratorFactory(allowsMaterial, elementHeader, autodiffWrapper=None)
Referenced by ikarus.finite_elements.LinearElastic.
def ikarus.finite_elements.LinearElastic(basis, element, youngsMod, nu, volumeLoad=None, bp=None, neumannBoundaryLoad=None)
def ikarus.finite_elements.KirchhoffLoveShell(basis, element, youngsMod, nu, thickness, volumeLoad=None, bp=None, neumannBoundaryLoad=None)
Referenced by Ikarus::Python::registerKirchhoffLoveShell.
def ikarus.finite_elements.NonLinearElastic(basis, element, material, volumeLoad=None, bp=None, neumannBoundaryLoad=None)
Referenced by Ikarus::Python::registerNonLinearElastic.