Ikarus::KirchhoffLoveShell
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::Traits = TraitsFromFE<Basis_, FERequirements_, useEigenRef>
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::Basis = typename Traits::Basis
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::FlatBasis = typename Traits::FlatBasis
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::FERequirementType = typename Traits::FERequirementType
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::LocalView = typename Traits::LocalView
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::Geometry = typename Traits::Geometry
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::GridView = typename Traits::GridView
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::Element = typename Traits::Element
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::ResultRequirementsType = typename Traits::ResultRequirementsType
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::BasePowerFE = PowerBasisFE<FlatBasis>
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::VolumeType = Volume<KirchhoffLoveShell<Basis_, FERequirements_, useEigenRef>, Traits>
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::TractionType = Traction<KirchhoffLoveShell<Basis_, FERequirements_, useEigenRef>, Traits>
using Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::RootBasis = Basis_::FlatBasis
Type of the root basis.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GlobalIndex = typename LocalView::MultiIndex
Type of the global index.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GridElement = typename LocalView::Element
Type of the grid element.
constexpr int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::myDim
constexpr int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::worldDim
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl.
constexpr int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::membraneStrainSize
constexpr int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::bendingStrainSize
constexpr int Ikarus::PowerBasisFE< Basis_::FlatBasis >::num_children
Number of children in the powerBasis.
std::shared_ptr<const Geometry> Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::localBasis
DefaultMembraneStrain Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::membraneStrain
double Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::emod_
double Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::nu_
double Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::thickness_
size_t Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::numberOfNodes_
int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::order_
Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::KirchhoffLoveShell(const Basis &globalBasis, const typename LocalView::Element &element, double emod, double nu, double thickness, VolumeLoad p_volumeLoad={}, const BoundaryPatch< GridView > *p_neumannBoundary=nullptr, NeumannBoundaryLoad p_neumannBoundaryLoad={})
Constructor for the KirchhoffLoveShell class.
Initializes the KirchhoffLoveShell instance with the given parameters. VolumeLoad The type representing the volume load function. NeumannBoundaryLoad The type representing the Neumann boundary load function. globalBasis The global basis for the finite element. element The local element to bind. emod Young's modulus of the material. nu Poisson's ratio of the material. thickness Thickness of the shell. p_volumeLoad The volume load function (optional, default is utils::LoadDefault). p_neumannBoundary The Neumann boundary patch (optional, default is nullptr). p_neumannBoundaryLoad The Neumann boundary load function (optional, default is LoadDefault).
auto Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Get the displacement function and nodal displacements.
Retrieves the displacement function and nodal displacements based on the given FERequirements. ScalarType The scalar type used for calculations. par The FERequirements. dx Optional additional displacement vector. The displacement function.
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl.
const Geometry & Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::geometry() const
size_t Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::numberOfNodes() const
int Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::order() const
double Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
void Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateAt(const ResultRequirementsType &req, const Dune::FieldVector< double, Traits::mydim > &local, ResultTypeMap< double > &result) const
Calculate results at local coordinates.
Calculates the results at the specified local coordinates based on the given requirements and stores them in the result container. req The result requirements. local The local coordinates at which results are to be calculated. result The result container to store the calculated values.
constexpr size_t Ikarus::PowerBasisFE< Basis_::FlatBasis >::size() const
Get the size of the local view.
The size of the local view.
void Ikarus::PowerBasisFE< Basis_::FlatBasis >::globalFlatIndices(std::vector< GlobalIndex > &globalIndices) const
Get the global flat indices for the power basis.
The global indices are collected in a FlatInterLeaved order. I.e. x_0, y_0, z_0, ..., x_n, y_n, z_n globalIndices Output vector to store global indices.
const GridElement & Ikarus::PowerBasisFE< Basis_::FlatBasis >::gridElement() const
Get the grid element associated with the local view.
The grid element.
const LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView() const
Get the const reference to the local view.
The const reference to the local view.
LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView()
Get the reference to the local view.
The reference to the local view.
double Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
double Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::computeMaterialAndStrains(const Dune::FieldVector< double, 2 > &gpPos, int gpIndex, const Geometry &geo, const auto &uFunction) const
Compute material properties and strains at a given integration point.
gpPos The position of the integration point. gpIndex The index of the integration point. geo The geometry object providing position and derivatives. uFunction The function representing the displacement field. gpPos The type of the integration point position. gpIndex The type of the integration point index. geo The type of the geometry object. uFunction The type of the displacement field function. A tuple containing the material tangent, membrane strain, bending, Jacobian matrix of the reference position, Jacobian matrix of the current position, Hessian matrix of the current position, Hessian matrix of the reference position, normal vector, and normalized normal vector at the given integration point.
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl.
void Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType< ScalarType > K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
Eigen::Matrix< ScalarType, 3, 3 > Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::kgBending(const Eigen::Matrix< ScalarType, 2, 3 > &jcur, const Eigen::Matrix3< ScalarType > &h, const auto &dN, const auto &ddN, const Eigen::Vector3< ScalarType > &a3N, const Eigen::Vector3< ScalarType > &a3, const Eigen::Vector3< ScalarType > &S, int I, int J) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl.
Eigen::Matrix< ScalarType, 3, 3 > Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::bopBending(const Eigen::Matrix< ScalarType, 2, 3 > &jcur, const Eigen::Matrix3< ScalarType > &h, const auto &dN, const auto &ddN, const int node, const Eigen::Vector3< ScalarType > &a3N, const Eigen::Vector3< ScalarType > &a3) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl.
Eigen::Matrix< double, 3, 3 > Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::materialTangent(const Eigen::Matrix< double, 3, 3 > &Aconv) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::computeMaterialAndStrains.
auto Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::Volume< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > dx=std::nullopt) const
void Ikarus::Traction< KirchhoffLoveShell< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const