Ikarus::LinearElastic
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::Traits = TraitsFromFE<Basis_, FERequirements_, useEigenRef>
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::Basis = typename Traits::Basis
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::FlatBasis = typename Traits::FlatBasis
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::FERequirementType = typename Traits::FERequirementType
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::LocalView = typename Traits::LocalView
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::Geometry = typename Traits::Geometry
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::GridView = typename Traits::GridView
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::Element = typename Traits::Element
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::ResultRequirementsType = typename Traits::ResultRequirementsType
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::BaseDisp = PowerBasisFE<FlatBasis>
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::VolumeType = Volume<LinearElastic<Basis_, FERequirements_, useEigenRef>, Traits>
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::TractionType = Traction<LinearElastic<Basis_, FERequirements_, useEigenRef>, Traits>
using Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::RootBasis = Basis_::FlatBasis
Type of the root basis.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GlobalIndex = typename LocalView::MultiIndex
Type of the global index.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GridElement = typename LocalView::Element
Type of the grid element.
constexpr int Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::myDim
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::materialTangent.
constexpr int Ikarus::PowerBasisFE< Basis_::FlatBasis >::num_children
Number of children in the powerBasis.
constexpr int Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::worldDim
constexpr int Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::worldDim
std::shared_ptr<const Geometry> Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::localBasis
double Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::emod_
double Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::nu_
size_t Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::numberOfNodes_
int Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::order_
Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::LinearElastic(const Basis &globalBasis, const typename LocalView::Element &element, double emod, double nu, VolumeLoad p_volumeLoad={}, const BoundaryPatch< GridView > *p_neumannBoundary=nullptr, NeumannBoundaryLoad p_neumannBoundaryLoad={})
Constructor for the LinearElastic class.
VolumeLoad The type for the volume load function. NeumannBoundaryLoad The type for the Neumann boundary load function. globalBasis The global basis for the finite element. element The element for which the finite element is constructed. emod Young's modulus. nu Poisson's ratio. p_volumeLoad Volume load function (default is LoadDefault). p_neumannBoundary Neumann boundary patch (default is nullptr). p_neumannBoundaryLoad Neumann boundary load function (default is LoadDefault).
auto Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Gets the displacement function for the given FERequirementType and optional displacement vector.
ScalarType The scalar type for the displacement vector. par The FERequirementType object. dx Optional displacement vector. The displacement function.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::strainFunction.
auto Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::strainFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Gets the strain function for the given FERequirementType and optional displacement vector.
ScalarType The scalar type for the strain vector. par The FERequirementType object. dx Optional displacement vector. The strain function.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl.
auto Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::materialTangent() const
Gets the material tangent matrix for the linear elastic material.
The material tangent matrix.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::materialTangentFunction.
auto Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::materialTangentFunction(const FERequirementType &par) const
Gets the material tangent function for the given FERequirementType.
par The FERequirementType object. The material tangent function.
const Geometry & Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::geometry() const
size_t Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::numberOfNodes() const
int Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::order() const
double Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalar(const FERequirementType &par) const
Calculates the scalar energy for the given FERequirementType.
par The FERequirementType object. The scalar energy.
void Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculates the vector force for the given FERequirementType.
par The FERequirementType object. force Vector to store the calculated force.
void Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculates the matrix stiffness for the given FERequirementType.
par The FERequirementType object. K Matrix to store the calculated stiffness.
void Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateAt(const ResultRequirementsType &req, const Dune::FieldVector< double, Traits::mydim > &local, ResultTypeMap< double > &result) const
Calculates results at a specific local position.
req The ResultRequirementsType object specifying the requested results. local Local position vector. result Map to store the calculated results.
constexpr size_t Ikarus::PowerBasisFE< Basis_::FlatBasis >::size() const
Get the size of the local view.
The size of the local view.
void Ikarus::PowerBasisFE< Basis_::FlatBasis >::globalFlatIndices(std::vector< GlobalIndex > &globalIndices) const
Get the global flat indices for the power basis.
The global indices are collected in a FlatInterLeaved order. I.e. x_0, y_0, z_0, ..., x_n, y_n, z_n globalIndices Output vector to store global indices.
const GridElement & Ikarus::PowerBasisFE< Basis_::FlatBasis >::gridElement() const
Get the grid element associated with the local view.
The grid element.
const LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView() const
Get the const reference to the local view.
The const reference to the local view.
LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView()
Get the reference to the local view.
The reference to the local view.
double Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
double Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::Volume< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > dx=std::nullopt) const
void Ikarus::Traction< LinearElastic< Basis_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const