Ikarus::EnhancedAssumedStrains
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::FERequirementType = typename DisplacementBasedElement::FERequirementType
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::ResultRequirementsType = typename DisplacementBasedElement::ResultRequirementsType
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::LocalView = typename DisplacementBasedElement::LocalView
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::GridView = typename DisplacementBasedElement::GridView
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::Traits = typename DisplacementBasedElement::Traits
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::EAS2DVariantImpl = EAS2DVariant<typename LocalView::Element::Geometry>
using Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::EAS3DVariantImpl = EAS3DVariant<typename LocalView::Element::Geometry>
std::conditional_t<Traits::mydim == 2, EAS2DVariantImpl, EAS3DVariantImpl> Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::easVariant_
Eigen::MatrixXd Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::L
Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::EnhancedAssumedStrains(Args &&... args)
Constructor for Enhanced Assumed Strains elements.
Disabling this forwarding constructor if the argument provided is EnhancedAssumedStrains itself, to forward the calls to the implicit copy constructor Args Variadic template for constructor arguments. args Constructor arguments forwarded to the base class.
double Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateScalar(const FERequirementType &par) const
Calculates a scalar quantity for the element.
This function calculates a scalar quantity for the element based on the FERequirementType. par The FERequirementType object. Computed scalar quantity.
bool Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::isDisplacementBased() const
Checks if the element is displacement-based and the EAS is turned off.
True if the element is displacement-based, false otherwise.
Referenced by Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateAt, Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateMatrix, Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateScalar, Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateScalarImpl, Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateVectorImpl, Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::setEASType.
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculates vectorial quantities for the element.
This function calculates the vectorial quantities for the element based on the FERequirementType. par The FERequirementType object. force Vector to store the calculated forces.
const auto & Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::easVariant() const
Gets the variant representing the type of Enhanced Assumed Strains (EAS).
Const reference to the EAS variant.
auto Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::getNumberOfEASParameters() const
Gets the number of EAS parameters based on the current EAS type.
Number of EAS parameters.
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculates the matrix for the element.
This function calculates the matrix for the element based on the FERequirementType. par The FERequirementType object. K Matrix to store the calculated stiffness.
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateAt(const ResultRequirementsType &req, const Dune::FieldVector< double, Traits::mydim > &local, ResultTypeMap< double > &result) const
Calculates the results at a given set of local coordinates using the Enhanced Assumed Strains (EAS) method.
This function calculates the results at the specified local coordinates . It takes into account the displacement-based element calculations and, if applicable, incorporates the EAS method for enhanced accuracy. req The result requirements. local The local coordinates at which results are to be calculated. result The result container to store the calculated values. ResultRequirementsType The type representing the requirements for results.
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::setEASType(int numberOfEASParameters_)
Sets the EAS type for 2D elements.
numberOfEASParameters_ The number of EAS parameters
ScalarType Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::EnhancedAssumedStrains< DisplacementBasedElement >::calculateDAndLMatrix(const auto &easFunction, const auto &par, Eigen::Matrix< double, enhancedStrainSize, enhancedStrainSize > &DMat, Eigen::MatrixXd &LMat) const