Ikarus::utils
constexpr bool Ikarus::utils::countTypeSpecialization_v
Variable template for counting the occurrences of a specialization of a template type in a tuple.
Type Template type to count occurrences for. Tuple Type of the tuple. This variable template provides a compile-time constant for the count of occurrences of a specialization of a template type in a tuple.
void Ikarus::utils::makeUniqueAndSort(std::ranges::random_access_range auto &r)
Sorts and removes duplicate elements from a random access range. *.
This function sorts the elements of the given random access range and removes duplicate elements, leaving only unique elements in the range. r The random access range to be modified.
auto Ikarus::utils::appendUnique(std::ranges::random_access_range auto &r, Value &&v)
Appends a value to the range if it is not already present.
This function appends a value to the given random access range only if the value is not already present in the range. It returns the index of the value in the range, whether it was added or already existed. Value The type of the value to be appended. r The random access range to be modified. v The value to be appended. The index of the value in the range.
void Ikarus::utils::printContent(Container &&c, std::ostream &os=std::cout)
Prints the contents of a container to the specified output stream.
This function prints the contents of the given container to the specified output stream. Container The type of the container to be printed. c The container whose contents will be printed. os The output stream where the contents will be printed. Default is std::cout.
auto Ikarus::utils::transformValueRangeToPointerRange(Container &cont)
Transforms a value range to a pointer range.
Container The type of the container containing values. cont The container whose values will be transformed to pointers. A subrange containing pointers to the values.
auto Ikarus::utils::transformPointerRangeToReferenceRange(Container &cont)
Transforms a pointer range to a reference range.
This function transforms a range of pointers to a range of references. Container The type of the container containing pointers. cont The container whose pointers will be transformed to references. A subrange containing references to the pointed objects.
constexpr size_t Ikarus::utils::find_if(Tuple &&tuple, Predicate pred)
Finds the index of the first element in the tuple satisfying a predicate.
Tuple Type of the input tuple. Predicate Type of the predicate function. tuple Input tuple. pred Predicate function to check each element. Index of the first element satisfying the predicate. If no element satisfies the predicate, it returns the size of the tuple. This function takes a tuple and a predicate function and finds the index of the first element in the tuple that satisfies the given predicate. It uses Dune::Hybrid::forEach to iterate through the tuple.
Referenced by findTypeSpecialization, hasTypeSpecialization, none_of.
bool Ikarus::utils::none_of(Tuple &&tuple, Predicate pred)
Checks if none of the elements in the tuple satisfy a given predicate.
Tuple Type of the input tuple. Predicate Type of the predicate function. tuple Input tuple. pred Predicate function to check each element. bool True if none of the elements satisfy the predicate, false otherwise.
Referenced by any_of.
bool Ikarus::utils::any_of(Tuple &&tuple, Predicate pred)
Checks if any of the elements in the tuple satisfy a given predicate.
Tuple Type of the input tuple. Predicate Type of the predicate function. tuple Input tuple. pred Predicate function to check each element. bool True if any of the elements satisfy the predicate, false otherwise.
auto Ikarus::utils::filter(Tuple &&tuple, Predicate pred)
Filters the elements of a tuple based on a given predicate.
Tuple Type of the input tuple. Predicate Type of the predicate function. tuple Input tuple. pred Predicate function to filter the elements. auto Tuple containing elements that satisfy the predicate. This function applies the given predicate to each element of the tuple. It constructs a new tuple containing only those elements for which the predicate returns true. The resulting tuple is returned.
constexpr auto Ikarus::utils::unique(std::tuple< Types... > &&tuple)
Creates a tuple with unique types from the given tuple.
Types Variadic template parameters representing types. tuple Input tuple. auto Tuple with unique types. This function takes a tuple and returns a new tuple containing only unique types from the input tuple.
Referenced by makeUniqueAndSort.
constexpr size_t Ikarus::utils::count_if(Tuple &&tuple, Predicate pred)
Counts the number of elements in the tuple satisfying the given predicate.
Tuple Type of the tuple. Predicate Predicate function determining whether an element satisfies the condition. tuple Input tuple. pred Predicate function. constexpr size_t Number of elements satisfying the predicate. This function counts the number of elements in the tuple that satisfy the given predicate.
Referenced by countTypeSpecialization.
constexpr int Ikarus::utils::findTypeSpecialization()
Finds the index of the first element in the tuple that is a specialization of the given template type.
Type Template type to search for. Tuple Type of the tuple. Index of the first specialization in the tuple This function finds the index of the first element in the tuple that is a specialization of the given template type. It returns the size of the tuple if the template type is not found
auto Ikarus::utils::getSpecialization(Tuple &&tuple)
Gets the specialization of the given template type from the tuple.
Type Template type to search for. Tuple Type of the tuple. tuple The tuple containing elements. The specialization element This function retrieves the specialization of a template type from the tuple.
constexpr bool Ikarus::utils::hasTypeSpecialization()
Checks if a tuple has a specialization of a template type.
Type Template type to check for. Tuple Type of the tuple. true if the tuple has the specialization; otherwise, false. This function checks if a tuple has a specialization of a template type. It uses find_if to search for the type and returns true if the index is less than the tuple size; otherwise, false.
constexpr bool Ikarus::utils::countTypeSpecialization()
Counts the occurrences of a specialization of a template type in a tuple.
Type Template type to count occurrences for. Tuple Type of the tuple. The count of occurrences of the specialization. This function counts the occurrences of a specialization of a template type in a tuple.
constexpr auto Ikarus::utils::makeTupleSubset(Tuple &&t)
Creates a subset tuple with the first N elements from the given tuple.
N Number of elements in the subset. Tuple Type of the original tuple. t The original tuple. A new tuple containing the first N elements of the original tuple. This function creates a subset tuple with the first N elements from the given tuple.
constexpr auto Ikarus::utils::makeTupleFromTupleIndices(Tuple &&t)
Creates a new tuple using indices from the original tuple.
Tuple Type of the original tuple. I Indices to include in the new tuple. t The original tuple. A new tuple containing elements from the original tuple based on the specified indices. This function creates a new tuple using indices from the original tuple. It uses makeTupleFromTupleIndicesImpl from the Impl namespace to implement the tuple creation.
auto Ikarus::utils::makeNestedTupleFlat(std::tuple< Types... >)
Creates a flattened nested tuple.
Types Types contained in the original tuple. A new flattened nested tuple.
auto Ikarus::utils::makeNestedTupleFlatAndStoreReferences(Tuple &&tup)
Creates a flattened nested tuple and stores references.
Tuple Type of the original tuple. tup The original tuple. A new tuple with stored references. This function creates a flattened nested tuple and stores references.
auto & Ikarus::utils::returnReferenceOrNulloptIfObjectIsNullPtr(T v)
Returns a reference or std::nullopt if the object is a nullptr.
T Type of the pointer. v Pointer value. Reference or std::nullopt.
void Ikarus::utils::hessianN(const Fun &f, const autodiff::Wrt< Vars... > &wrt, const autodiff::At< Args... > &at, U &u, std::array< G, U::RowsAtCompileTime > &g, std::array< H, U::RowsAtCompileTime > &h)
Computes the Hessian matrix for each parameter of a given function. The Hessian matrix represents the second-order partial derivatives of the function with respect to the specified variables.
Fun The type of the function to be differentiated. Vars The types of the variables with respect to which the Hessian is computed. Args The types of the arguments passed to the function. U The type representing the result of the function evaluation. G The type representing the gradient of the function. H The type representing the Hessian matrix. f The function to be differentiated. wrt The variables with respect to which the Hessian is computed. at The values at which the Hessian is evaluated. u The result of the function evaluation. g The gradient of the function. h The Hessian matrix (output).
std::tuple< Dune::Functions::Polynomial< double >, decltype(Eigen::seq(0, 0))> Ikarus::utils::findLineSegment(const Eigen::VectorXd &x, const Eigen::VectorXd &y, int segmentSize)
Find a linear segment in a set of data points.
his function is inspired by the MATLAB code at: https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/identify_linear_piece.m It is designed to find the most linear segment in a set of data points x The x-coordinates of the data points. y The y-coordinates of the data points. segmentSize The size of the line segment to be identified. A tuple containing the polynomial representing the identified line segment and the indices of the data points in the segment.
void Ikarus::utils::obtainLagrangeNodePositions(const LocalView &localView, std::vector< Dune::FieldVector< double, size > > &lagrangeNodeCoords)
A function to obtain the global positions of the nodes of an element with Lagrangian basis, see Dune book page 314.
size Size of the nodal coordinate vector LocalView Type of the local view localView Local view bounded to an element lagrangeNodeCoords A vector of nodal coordinates to be updated
bool Ikarus::utils::checkGradient(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the gradient of a nonlinear operator.
The checkgradient function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 4.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkdiff.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
bool Ikarus::utils::checkJacobian(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the Jacobian of a nonlinear operator.
The checkjacobian function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 4.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkdiff.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
bool Ikarus::utils::checkHessian(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the Hessian of a nonlinear operator.
The checkHessian function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 6.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkhessian.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
std::tuple< Dune::Functions::Polynomial< double >, double > Ikarus::utils::polyfit(const Eigen::Ref< const Eigen::VectorXd > &x, const Eigen::Ref< const Eigen::VectorXd > &y, int deg)
Fits a polynomial of a given degree to the given data points.
x The input vector of x-coordinates. y The input vector of y-coordinates. deg The degree of the polynomial to fit. std::tuple<Dune::Functions::Polynomial<double>, double> A tuple containing the fitted polynomial and the least square error.