utils
constexpr auto Ikarus::voigtNotationContainer
Container for Voigt notation indices based on dimension. 1D: 0,0 2D: 0,0; 1,1; 0,1 3D: 0,0; 1,1; 2,2; 1,2; 0,2; 0,1.
dim The dimension for which Voigt indices are needed.
void Ikarus::utils::hessianN(const Fun &f, const autodiff::Wrt< Vars... > &wrt, const autodiff::At< Args... > &at, U &u, std::array< G, U::RowsAtCompileTime > &g, std::array< H, U::RowsAtCompileTime > &h)
Computes the Hessian matrix for each parameter of a given function. The Hessian matrix represents the second-order partial derivatives of the function with respect to the specified variables.
Fun The type of the function to be differentiated. Vars The types of the variables with respect to which the Hessian is computed. Args The types of the arguments passed to the function. U The type representing the result of the function evaluation. G The type representing the gradient of the function. H The type representing the Hessian matrix. f The function to be differentiated. wrt The variables with respect to which the Hessian is computed. at The values at which the Hessian is evaluated. u The result of the function evaluation. g The gradient of the function. h The Hessian matrix (output).
std::tuple< Dune::Functions::Polynomial< double >, decltype(Eigen::seq(0, 0))> Ikarus::utils::findLineSegment(const Eigen::VectorXd &x, const Eigen::VectorXd &y, int segmentSize)
Find a linear segment in a set of data points.
his function is inspired by the MATLAB code at: https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/identify_linear_piece.m It is designed to find the most linear segment in a set of data points x The x-coordinates of the data points. y The y-coordinates of the data points. segmentSize The size of the line segment to be identified. A tuple containing the polynomial representing the identified line segment and the indices of the data points in the segment.
decltype(auto) Ikarus::flatPreBasis(const PreBasis &preBasis)
Generator function for a flatted PreBasis.
void Ikarus::utils::obtainLagrangeNodePositions(const LV &localView, std::vector< Dune::FieldVector< double, size > > &lagrangeNodeCoords)
A function to obtain the global positions of the nodes of an element with Lagrangian basis, see Dune book page 314.
size Size of the nodal coordinate vector LV Type of the local view localView Local view bounded to an element lagrangeNodeCoords A vector of nodal coordinates to be updated
auto Ikarus::utils::referenceElementSubEntityPositions(FE &fe, int codim)
A function to obtain the local coordinates of subentities of an FiniteElement.
FE Type of the finite element fe finite element codim codim of requested subentity view over the position of the subenties
Referenced by Ikarus::utils::referenceElementVertexPositions.
auto Ikarus::utils::referenceElementVertexPositions(FE &fe)
A function to obtain the local coordinates the vertices of an FiniteElement.
FE Type of the finite element fe finite element
bool Ikarus::utils::checkGradient(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the gradient of a nonlinear operator.
The checkgradient function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 4.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkdiff.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
bool Ikarus::utils::checkJacobian(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the Jacobian of a nonlinear operator.
The checkjacobian function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 4.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkdiff.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
bool Ikarus::utils::checkHessian(NonlinearOperator &nonLinOp, CheckFlags checkFlags=CheckFlags(), std::function< void(typename NonlinearOperator::template ParameterValue< 0 > &, const UpdateType &)> p_updateFunction=[](typename NonlinearOperator::template ParameterValue< 0 > &a, const UpdateType &b) { a+=b;})
Checks the Hessian of a nonlinear operator.
The checkHessian function is inspired by http://sma.epfl.ch/~nboumal/book/ Chapter 6.8 and https://github.com/NicolasBoumal/manopt/blob/master/manopt/tools/checkhessian.m NonlinearOperator Type of the nonlinear operator. UpdateType Type of the update. nonLinOp The nonlinear operator. checkFlags Flags for the check. p_updateFunction Update function. True if the check passed, false otherwise.
auto Ikarus::orthonormalizeMatrixColumns(const Eigen::MatrixBase< Derived > &A)
Orthonormalizes all Matrix columns using Gram-Schmidt Orthogonalization.
Derived Type of the input matrix. A The input matrix. Eigen Matrix with orthonormalized columns.
auto Ikarus::viewAsFlatEigenVector(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Vector.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a flat Eigen::Vector.
Referenced by Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateAtImpl, Ikarus::EnhancedAssumedStrains< PreFE, FE >::calculateVectorImpl.
auto Ikarus::viewAsFlatEigenVector(const Dune::BlockVector< ValueType > &blockedVector)
View const Dune::BlockVector as an Eigen::Vector.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a flat Eigen::Vector (const version).
auto Ikarus::viewAsEigenMatrixAsDynFixed(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Matrix with dynamic rows and fixed columns depending on the size of the ValueType.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a dynamic Eigen::Matrix.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::computeMaterialAndStrains.
auto Ikarus::viewAsEigenMatrixAsDynFixed(const Dune::BlockVector< ValueType > &blockedVector)
Const view Dune::BlockVector as an Eigen::Matrix with dynamic rows and fixed columns depending on the size of the ValueType.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a dynamic Eigen::Matrix (const version).
auto Ikarus::viewAsEigenMatrixFixedDyn(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Matrix with fixed rows depending on the size of the ValueType and dynamic columns.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a fixed-size Eigen::Matrix with dynamic columns.
auto Ikarus::viewAsEigenMatrixFixedDyn(const Dune::BlockVector< ValueType > &blockedVector)
Const view Dune::BlockVector as an Eigen::Matrix with fixed rows depending on the size of the ValueType and dynamic columns.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a fixed-size Eigen::Matrix with dynamic columns (const version).
size_t Ikarus::correctionSize(const Dune::BlockVector< Type > &a)
Returns the total correction size of a block vector with a Manifold as the underlying type.
Type Manifold type. a Input Dune::BlockVector. Total correction size.
Referenced by Ikarus::correctionSize, Ikarus::operator+=, Ikarus::operator-=.
size_t Ikarus::valueSize(const Dune::BlockVector< Type > &a)
Returns the total value size of a block vector with a Manifold as the underlying type.
Type Manifold type. a Input Dune::BlockVector. Total value size.
Referenced by Ikarus::addInEmbedding, Ikarus::valueSize.
Dune::BlockVector< Type > & Ikarus::operator+=(Dune::BlockVector< Type > &a, const Eigen::MatrixBase< Derived > &b)
Enables the += operator for Dune::BlockVector += Eigen::Vector.
Type Manifold type. Derived Type of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
Dune::BlockVector< Type > & Ikarus::operator-=(Dune::BlockVector< Type > &a, const Eigen::MatrixBase< Derived > &b)
Enables the -= operator for Dune::BlockVector += Eigen::Vector.
Type Manifold type. Derived Type of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
Dune::TupleVector< Types... > & Ikarus::operator+=(Dune::TupleVector< Types... > &a, const Eigen::MatrixBase< Derived > &b)
Enables the += operator for Dune::TupleVector += Eigen::Vector.
Types Types of the elements in the TupleVector. Derived Type of the input Eigen matrix. a Input Dune::TupleVector. b Input Eigen::Matrix. Reference to the modified Dune::TupleVector.
Dune::BlockVector< ManifoldPoint > & Ikarus::addInEmbedding(Dune::BlockVector< ManifoldPoint > &a, const Eigen::MatrixBase< Derived > &b)
Enables the addition in the embedding space of a vector in the space M^n, where M is a manifold with the points of type ManifoldPoint.
ManifoldPoint Manifold type. Derived ManifoldPoint of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
auto Ikarus::norm(const Eigen::MatrixBase< Derived > &v)
Adding free norm function to Eigen types.
Derived Type of the input Eigen matrix. v Input Eigen matrix. Norm of the matrix.
auto Ikarus::norm(const std::floating_point auto &v)
Helper Free Function to have the same interface as for Eigen Vector Types.
v Input scalar. Absolute value of the scalar.
auto Ikarus::operator*(const Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
Eigen::DiagonalMatrix Product Missing in Eigen.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input DiagonalMatrix. Product of the two DiagonalMatrices.
auto Ikarus::operator+=(Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
In-place addition for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input DiagonalMatrix. Reference to the modified DiagonalMatrix.
auto Ikarus::operator+(const Eigen::MatrixBase< Derived > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
Eigen::Matrix + Eigen::DiagonalMatrix addition missing in Eigen.
Derived Type of the input Eigen matrix. Scalar Scalar type. size Size of the diagonal matrix. a Input Eigen matrix. b Input DiagonalMatrix. Sum of the Eigen matrix and DiagonalMatrix.
auto Ikarus::operator+(const Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::MatrixBase< Derived > &b)
Eigen::DiagonalMatrix + Eigen::Matrix addition missing in Eigen.
Derived Type of the input Eigen matrix. Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input Eigen matrix. Sum of the DiagonalMatrix and Eigen matrix.
auto Ikarus::operator-(const Eigen::DiagonalMatrix< Scalar, size > &a)
Unary minus for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. Negation of the DiagonalMatrix.
auto Ikarus::operator+(const Eigen::MatrixBase< Derived > &a, const Eigen::DiagonalWrapper< Derived2 > &b)
Addition of Eigen::Matrix and Eigen::DiagonalWrapper.
Derived Type of the input Eigen matrix. Derived2 Type of the input Eigen DiagonalWrapper. a Input Eigen matrix. b Input Eigen DiagonalWrapper. Sum of Eigen matrix and DiagonalWrapper.
auto Ikarus::operator+(const Eigen::DiagonalWrapper< Derived > &a, const Eigen::MatrixBase< Derived2 > &b)
Addition of Eigen::DiagonalWrapper and Eigen::Matrix.
Derived Type of the input Eigen DiagonalWrapper. Derived2 Type of the input Eigen matrix. a Input Eigen DiagonalWrapper. b Input Eigen matrix. Sum of DiagonalWrapper and Eigen matrix.
std::ostream & Ikarus::operator<<(std::ostream &os, const Eigen::DiagonalMatrix< Scalar, size > &a)
Output stream operator for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. os Output stream. a Input DiagonalMatrix. Reference to the output stream.
Derived Ikarus::sym(const Eigen::MatrixBase< Derived > &A)
Returns the symmetric part of a matrix.
Derived Type of the input Eigen matrix. A Input Eigen matrix. Symmetric part of the matrix.
Derived Ikarus::skew(const Eigen::MatrixBase< Derived > &A)
Returns the skew part of a matrix.
Derived Type of the input Eigen matrix. A Input Eigen matrix. Skew part of the matrix.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::kgBending.
void Ikarus::printForMaple(const Eigen::EigenBase< Derived > &A)
Method to print the matrix in a format that can directly be copied to Maple.
Derived The derived type of the matrix. A The input matrix.
auto Ikarus::createRandomVector(typename FieldVectorT::value_type lower=-1, typename FieldVectorT::value_type upper=1)
Creates a random vector of the specified type within a given range.
FieldVectorT The type of the vector. lower The lower bound of the random values (default is -1). upper The upper bound of the random values (default is 1). A random vector within the specified range.
Eigen::Matrix< ScalarType, 3, 3 > Ikarus::skew(const Eigen::Vector< ScalarType, 3 > &a)
Create skew 3x3 matrix from 3d vector.
ScalarType The type of the coordinates in the vector. a The vector. The skew matrix.
auto Ikarus::staticCondensation(const Eigen::MatrixBase< Derived > &E, const std::array< size_t, sizeOfCondensedIndices > &indices)
Performs static condensation on a square matrix.
Derived Type of the matrix. sizeOfCondensedIndices Size of the condensed indices. E Input matrix. indices Array of indices to be condensed. Resulting matrix after static condensation. This function performs static condensation on a square matrix. It removes the specified indices from the matrix, computes the remaining submatrices (K11, K12, K22), and returns the result of the static condensation.
Referenced by Ikarus::VanishingStress< stressIndexPair, MI >::tangentModuliImpl.
auto Ikarus::removeCol(const Eigen::MatrixBase< Derived > &E, const std::array< size_t, sizeOfRemovedCols > &indices)
Removes specified columns from a matrix.
Derived Type of the matrix. sizeOfRemovedCols Size of the columns to be removed. E Input matrix. indices Array of column indices to be removed. Resulting matrix after removing specified columns. This function removes specified columns from a matrix. It computes the remaining columns after removing the specified indices and returns the resulting matrix.
Referenced by Ikarus::VanishingStress< stressIndexPair, MI >::stressesImpl, Ikarus::toVoigtAndMaybeReduce.
auto Ikarus::toVoigtAndMaybeReduce(const Eigen::Matrix< ST, 3, 3 > &E, const MaterialImpl &material, bool isStrain=true)
Converts a 3x3 matrix to Voigt notation, possibly reducing it based on material properties.
ST Scalar type of the matrix. MaterialImpl Type of the material implementation. E Input 3x3 matrix. material Reference to the material implementation. isStrain Flag indicating if the matrix represents strain (default is true). Resulting matrix in Voigt notation. This function converts a 3x3 matrix to its Voigt notation. If the material is not reduced, the full Voigt notation is returned. Otherwise, the specified columns (based on material properties, such as VanishingStress) are removed, and the reduced Voigt notation is returned.
decltype(auto) Ikarus::enlargeIfReduced(const Eigen::MatrixBase< Derived > &E)
Enlarges a matrix if it reduced in the context of material laws, i.e., VanishingStress If the material is not reduced the untouched matrix is returned and rendering the function as a NoOp.
M Type of the material. Derived Type of the input matrix. E Input matrix. auto Resulting matrix based on material properties. This function takes an input matrix and, based on the material properties, either returns the original matrix (if it is not reduced) or enlarges the matrix by filling in the specified columns with zeros (if it is reduced).
MessageType & Ikarus::increment(MessageType &e)
Increments the given enum value.
MessageType The enum type. e The enum value to increment. The incremented enum value. Dune::RangeError if trying to increment MessageType::END.
Referenced by Ikarus::IObservable< MessageType >::IObservable.
std::tuple< Dune::Functions::Polynomial< double >, double > Ikarus::utils::polyfit(const Eigen::Ref< const Eigen::VectorXd > &x, const Eigen::Ref< const Eigen::VectorXd > &y, int deg)
Fits a polynomial of a given degree to the given data points.
x The input vector of x-coordinates. y The input vector of y-coordinates. deg The degree of the polynomial to fit. std::tuple<Dune::Functions::Polynomial<double>, double> A tuple containing the fitted polynomial and the least square error.
MAKE_ENUM
Macro to create an enumeration with a string conversion function. The macro creates an enum class with a BEGIN and END enumerator, and provides a constexpr toString function for string conversion.
type The name of the enum class. ... Enumerators to be included between BEGIN and END.