Ikarus
ScalarAffordances
VectorAffordances
MatrixAffordances
FEParameter
FESolutions
ResultType
StrainTags
StressTags
TangentModuliTags
SolverTypeTag
MatrixTypeTag
PreConditioner
StopReason
ControlMessages
NonLinearSolverMessages
using Ikarus::LinearElasticity = typedef LinearElasticityT<double>
Convenience typedef for LinearElasticity with double as ScalarType.
using Ikarus::NeoHooke = typedef NeoHookeT<double>
Alias for NeoHookeT with double as the default scalar type.
using Ikarus::StVenantKirchhoff = typedef StVenantKirchhoffT<double>
Alias for StVenantKirchhoffT with double as the default scalar type.
using Ikarus::LinearSolver = typedef LinearSolverTemplate<double>
using Ikarus::FlatPreBasis_t = typedef typename FlatPreBasis<PreBasis>::type
Type alias for flatted PreBasis.
constexpr VectorAffordances Ikarus::forces
Referenced by PYBIND11_MODULE.
constexpr MatrixAffordances Ikarus::stiffness
Referenced by PYBIND11_MODULE.
constexpr MatrixAffordances Ikarus::stiffnessdiffBucklingVector
Referenced by PYBIND11_MODULE.
constexpr MatrixAffordances Ikarus::mass
Referenced by PYBIND11_MODULE.
constexpr ScalarAffordances Ikarus::potentialEnergy
constexpr auto Ikarus::voigtNotationContainer
Container for Voigt notation indices based on dimension. 1D: 0,0 2D: 0,0; 1,1; 0,1 3D: 0,0; 1,1; 2,2; 1,2; 0,2; 0,1.
dim The dimension for which Voigt indices are needed.
constexpr std::string Ikarus::toString(ScalarAffordances _e)
Referenced by Ikarus::FERequirements< SV, PM >::getGlobalSolution, Ikarus::FERequirements< SV, PM >::getParameter, Ikarus::ResultFunction< FE, resType, UserFunction >::name.
constexpr std::string Ikarus::toString(VectorAffordances _e)
constexpr std::string Ikarus::toString(MatrixAffordances _e)
constexpr std::string Ikarus::toString(FEParameter _e)
constexpr std::string Ikarus::toString(FESolutions _e)
constexpr std::string Ikarus::toString(ResultType _e)
consteval bool Ikarus::hasCorrectSize()
Template function for checking if the strain size is correct.
The given strain quantity has to be a Eigen::Vector6 or a Eigen::Matrix3 MAT Type of the material. S Type of the strains.
auto Ikarus::createGreenLagrangianStrains(const Eigen::MatrixBase< Derived > &eMB)
Create Green-Lagrangian strain based on the input.
This function creates Green-Lagrangian strains based on the input strain matrix. What to do is decided by the provided strain tag tag Type of the strain tag. Derived Type of the Eigen matrix. eMB Eigen matrix representing the input strain. The Green-Lagrangian strains matrix.
decltype(auto) Ikarus::createDeformationGradient(const Eigen::MatrixBase< Derived > &eMB)
Create the deformation gradient based on the input.
This function creates deformation gradient based on the input strain matrix. What to do is decided by the provided strain tag tag Type of the strain tag. Derived Type of the Eigen matrix. eMB Eigen matrix representing the input strain. The deformation gradient matrix.
decltype(auto) Ikarus::createRightCauchyGreen(const Eigen::MatrixBase< Derived > &eMB)
Create right Cauchy-Green tensor based on the input.
This function creates Right Cauchy-Green tensor based on the input strain matrix. What to do is decided by the provided strain tag tag Type of the strain tag. Derived Type of the Eigen matrix. eMB Eigen matrix representing the input strain. The Right Cauchy-Green tensor matrix.
decltype(auto) Ikarus::transformStrain(const Eigen::MatrixBase< Derived > &eRaw)
Transform strain from one type to another.
This function transforms one strain component matrix from one type to another, based on the provided strain tags from Type of the source strain tag. to Type of the target strain tag. Derived Type of the Eigen matrix. eRaw Eigen matrix representing the input strain. The transformed strain matrix.
constexpr std::string Ikarus::toString(StrainTags _e)
constexpr std::string Ikarus::toString(StressTags _e)
constexpr std::string Ikarus::toString(TangentModuliTags _e)
auto Ikarus::makeVanishingStress(MaterialImpl mat, typename MaterialImpl::ScalarType p_tol=1e-12)
Factory function to create a VanishingStress material with specified stress indices.
stressIndexPair The array of StressIndexPair representing fixed stress components. MaterialImpl The underlying material model. mat The underlying material model. p_tol Tolerance for stress reduction. VanishingStress The created VanishingStress material.
Referenced by beamMaterial, planeStress, shellMaterial.
auto Ikarus::planeStress(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for plane stress conditions.
MaterialImpl The underlying material model. mat The underlying material model. tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.
auto Ikarus::shellMaterial(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for a shell material with zero normal stress condition.
MaterialImpl The underlying material model. mat The underlying material model. tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.
auto Ikarus::beamMaterial(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for a beam material with two zero normal stress condition.
MaterialImpl The underlying material model. mat The underlying material model. p_tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.
Eigen::Matrix3d Ikarus::planeStressLinearElasticMaterialTangent(double E, double nu)
Computes the plane stress linear elastic material tangent matrix.
E Young's modulus. nu Poisson's ratio. 3x3 material tangent matrix.
Referenced by Ikarus::LinearElastic< B, FER, useEigenRef >::materialTangent.
Eigen::Matrix< double, 6, 6 > Ikarus::linearElasticMaterialTangent3D(double E, double nu)
Computes the 3D linear elastic material tangent matrix.
E Young's modulus. nu Poisson's ratio. 6x6 material tangent matrix. Structure representing Young's modulus and Poisson's ratio. see https://en.wikipedia.org/wiki/Lam%C3%A9_parameters
Referenced by Ikarus::LinearElastic< B, FER, useEigenRef >::materialTangent.
ConvertLameConstants< YoungsModulusAndPoissonsRatio > Ikarus::convertLameConstants(const YoungsModulusAndPoissonsRatio &valuePair)
Referenced by toLamesFirstParameterAndShearModulus, toYoungsModulusAndPoissonsRatio.
ConvertLameConstants< YoungsModulusAndShearModulus > Ikarus::convertLameConstants(const YoungsModulusAndShearModulus &valuePair)
ConvertLameConstants< YoungsModulusAndBulkModulus > Ikarus::convertLameConstants(const YoungsModulusAndBulkModulus &valuePair)
ConvertLameConstants< LamesFirstParameterAndShearModulus > Ikarus::convertLameConstants(const LamesFirstParameterAndShearModulus &valuePair)
ConvertLameConstants< BulkModulusAndLamesFirstParameter > Ikarus::convertLameConstants(const BulkModulusAndLamesFirstParameter &valuePair)
auto Ikarus::toLamesFirstParameterAndShearModulus(const YoungsModulusAndPoissonsRatio &matParameter)
Converts Young's modulus and Poisson's ratio to Lame's first parameter and shear modulus.
matParameter Young's modulus and Poisson's ratio. Lame's first parameter and shear modulus.
auto Ikarus::toYoungsModulusAndPoissonsRatio(const LamesFirstParameterAndShearModulus &matParameter)
Converts Lame's first parameter and shear modulus to Young's modulus and Poisson's ratio.
matParameter Lame's first parameter and shear modulus. Young's modulus and Poisson's ratio.
auto Ikarus::makeNewtonRaphson(const NLO &nonLinearOperator, LS &&linearSolver={}, UF &&updateFunction={})
Function to create a NewtonRaphson solver instance.
NLO Type of the nonlinear operator to solve. LS Type of the linear solver used internally (default is SolverDefault). UF Type of the update function (default is UpdateDefault). nonLinearOperator Nonlinear operator to solve. linearSolver Linear solver used internally (default is SolverDefault). updateFunction Update function (default is UpdateDefault). Shared pointer to the NewtonRaphson solver instance.
auto Ikarus::makeNewtonRaphsonWithSubsidiaryFunction(const NLO &nonLinearOperator, LS &&linearSolver={}, UF &&updateFunction={})
Function to create a NewtonRaphson with subsidiary function solver instance.
NLO Type of the nonlinear operator to solve. LS Type of the linear solver used internally (default is SolverDefault). UF Type of the update function (default is UpdateDefault). nonLinearOperator Nonlinear operator to solve. linearSolver Linear solver used internally (default is SolverDefault). updateFunction Update function (default is UpdateDefault). Shared pointer to the NewtonRaphson solver instance.
auto Ikarus::makeTrustRegion(const NLO &nonLinearOperator, UF &&updateFunction={})
Creates an instance of the TrustRegion solver.
NLO Type of the nonlinear operator to solve. preConditioner Type of the preconditioner used internally (default is IncompleteCholesky). UF Type of the update function (default is UpdateDefault). nonLinearOperator Nonlinear operator to solve. updateFunction Update function (default is UpdateDefault). Shared pointer to the TrustRegion solver instance.
auto Ikarus::makeBasis(const GV &gv, const PBF &pb)
Factory function to create a Basis object.
Factory function that creates a Basis object from a given grid view and pre-basis factory. GV The type of the grid view. PBF The type of the pre-basis factory function. gv The grid view. pb The pre-basis factory function. A Basis object.
auto Ikarus::makeBasis(const Dune::Functions::DefaultGlobalBasis< PB > &gb)
Factory function to create a Basis object from a DefaultGlobalBasis.
PB The type of the pre-basis associated with the DefaultGlobalBasis. gb The DefaultGlobalBasis. A Basis object.
auto Ikarus::transpose(const Eigen::EigenBase< Derived > &A)
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::bopBending.
Dune::FieldVector< ST, size > Ikarus::toDune(const Eigen::Vector< ST, size > &vec)
Create Eigen::Vector to Dune::FieldVector.
ST The scalar type of the vectors. size The size of the vectors. vec The Eigen::Vector to be converted. Dune::FieldVector<ST, size> representing the converted vector.
Dune::FieldVector< ST, rows > Ikarus::toDune(const Eigen::Matrix< ST, rows, 0 > &vec)
Convert Eigen::Matrix to Dune::FieldVector.
The matrix has fixed row size. The matrix needs to have a single column. ST The scalar type of the vectors. rows The number of rows in the matrix. vec The Eigen::Matrix to be converted. Dune::FieldVector<ST, rows> representing the converted matrix.
Dune::FieldMatrix< ST, rows, cols > Ikarus::toDune(const Eigen::Matrix< ST, rows, cols > &mat)
Convert Eigen::Matrix to Dune::FieldMatrix.
The matrix has fixed rows and column size ST The scalar type of the matrix. rows The number of rows in the matrix. cols The number of columns in the matrix. mat The Eigen::Matrix to be converted. Dune::FieldMatrix<ST, rows, cols> representing the converted matrix.
Eigen::Map< const Eigen::Vector< ST, size > > Ikarus::toEigenMap(const Dune::FieldVector< ST, size > &vec)
View a Dune::FieldVector as an Eigen::Vector using Map, no copies take place.
ST The scalar type of the vector. size The size of the vector. vec The Dune::FieldVector to be viewed as Eigen::Vector. Eigen::Map<const Eigen::Vector<ST, size>> representing the viewed vector.
Eigen::Map< Eigen::Vector< ST, size > > Ikarus::toEigenMap(Dune::FieldVector< ST, size > &vec)
View a constant Dune::FieldVector as a constant Eigen::Vector, no copies take place.
ST The scalar type of the vector. size The size of the vector. vec The Dune::FieldVector to be viewed as Eigen::Vector. Eigen::Map<Eigen::Vector<ST, size>> representing the viewed vector.
decltype(auto) Ikarus::flatPreBasis(const PreBasis &preBasis)
Generator function for a flatted PreBasis.
void Ikarus::init(int argc, char **argv, bool enableFileLogger=true)
Initializes the Ikarus framework.
argc The number of command-line arguments. argv The command-line arguments. enableFileLogger Flag indicating whether to enable the file logger.
Referenced by PYBIND11_MODULE, Ikarus::Python::registerBasis, Ikarus::Python::registerBoundaryPatch, Ikarus::Python::registerDirichletValues, Ikarus::Python::registerElement, Ikarus::Python::registerKirchhoffLoveShell, Ikarus::Python::registerNonLinearElastic.
auto Ikarus::orthonormalizeMatrixColumns(const Eigen::MatrixBase< Derived > &A)
Orthonormalizes all Matrix columns using Gram-Schmidt Orthogonalization.
Derived Type of the input matrix. A The input matrix. Eigen Matrix with orthonormalized columns.
auto Ikarus::viewAsFlatEigenVector(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Vector.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a flat Eigen::Vector.
Referenced by Ikarus::EnhancedAssumedStrains< DFE >::calculateAt, Ikarus::EnhancedAssumedStrains< DFE >::calculateVectorImpl.
auto Ikarus::viewAsFlatEigenVector(const Dune::BlockVector< ValueType > &blockedVector)
View const Dune::BlockVector as an Eigen::Vector.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a flat Eigen::Vector (const version).
auto Ikarus::viewAsEigenMatrixAsDynFixed(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Matrix with dynamic rows and fixed columns depending on the size of the ValueType.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a dynamic Eigen::Matrix.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::computeMaterialAndStrains.
auto Ikarus::viewAsEigenMatrixAsDynFixed(const Dune::BlockVector< ValueType > &blockedVector)
Const view Dune::BlockVector as an Eigen::Matrix with dynamic rows and fixed columns depending on the size of the ValueType.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a dynamic Eigen::Matrix (const version).
auto Ikarus::viewAsEigenMatrixFixedDyn(Dune::BlockVector< ValueType > &blockedVector)
View Dune::BlockVector as an Eigen::Matrix with fixed rows depending on the size of the ValueType and dynamic columns.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a fixed-size Eigen::Matrix with dynamic columns.
auto Ikarus::viewAsEigenMatrixFixedDyn(const Dune::BlockVector< ValueType > &blockedVector)
Const view Dune::BlockVector as an Eigen::Matrix with fixed rows depending on the size of the ValueType and dynamic columns.
ValueType Type of the elements in the BlockVector. blockedVector Input Dune::BlockVector. Eigen::Map of the BlockVector as a fixed-size Eigen::Matrix with dynamic columns (const version).
size_t Ikarus::correctionSize(const Dune::BlockVector< Type > &a)
Returns the total correction size of a block vector with a Manifold as the underlying type.
Type Manifold type. a Input Dune::BlockVector. Total correction size.
Referenced by correctionSize, operator+=, operator-=.
size_t Ikarus::valueSize(const Dune::BlockVector< Type > &a)
Returns the total value size of a block vector with a Manifold as the underlying type.
Type Manifold type. a Input Dune::BlockVector. Total value size.
Referenced by addInEmbedding, valueSize.
Dune::BlockVector< Type > & Ikarus::operator+=(Dune::BlockVector< Type > &a, const Eigen::MatrixBase< Derived > &b)
Enables the += operator for Dune::BlockVector += Eigen::Vector.
Type Manifold type. Derived Type of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
Dune::BlockVector< Type > & Ikarus::operator-=(Dune::BlockVector< Type > &a, const Eigen::MatrixBase< Derived > &b)
Enables the -= operator for Dune::BlockVector += Eigen::Vector.
Type Manifold type. Derived Type of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
Dune::TupleVector< Types... > & Ikarus::operator+=(Dune::TupleVector< Types... > &a, const Eigen::MatrixBase< Derived > &b)
Enables the += operator for Dune::TupleVector += Eigen::Vector.
Types Types of the elements in the TupleVector. Derived Type of the input Eigen matrix. a Input Dune::TupleVector. b Input Eigen::Matrix. Reference to the modified Dune::TupleVector.
Dune::BlockVector< ManifoldPoint > & Ikarus::addInEmbedding(Dune::BlockVector< ManifoldPoint > &a, const Eigen::MatrixBase< Derived > &b)
Enables the addition in the embedding space of a vector in the space M^n, where M is a manifold with the points of type ManifoldPoint.
ManifoldPoint Manifold type. Derived ManifoldPoint of the input Eigen matrix. a Input Dune::BlockVector. b Input Eigen::Matrix. Reference to the modified Dune::BlockVector.
auto Ikarus::norm(const Eigen::MatrixBase< Derived > &v)
Adding free norm function to Eigen types.
Derived Type of the input Eigen matrix. v Input Eigen matrix. Norm of the matrix.
auto Ikarus::norm(const std::floating_point auto &v)
Helper Free Function to have the same interface as for Eigen Vector Types.
v Input scalar. Absolute value of the scalar.
auto Ikarus::operator*(const Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
Eigen::DiagonalMatrix Product Missing in Eigen.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input DiagonalMatrix. Product of the two DiagonalMatrices.
auto Ikarus::operator+=(Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
In-place addition for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input DiagonalMatrix. Reference to the modified DiagonalMatrix.
auto Ikarus::operator+(const Eigen::MatrixBase< Derived > &a, const Eigen::DiagonalMatrix< Scalar, size > &b)
Eigen::Matrix + Eigen::DiagonalMatrix addition missing in Eigen.
Derived Type of the input Eigen matrix. Scalar Scalar type. size Size of the diagonal matrix. a Input Eigen matrix. b Input DiagonalMatrix. Sum of the Eigen matrix and DiagonalMatrix.
auto Ikarus::operator+(const Eigen::DiagonalMatrix< Scalar, size > &a, const Eigen::MatrixBase< Derived > &b)
Eigen::DiagonalMatrix + Eigen::Matrix addition missing in Eigen.
Derived Type of the input Eigen matrix. Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. b Input Eigen matrix. Sum of the DiagonalMatrix and Eigen matrix.
auto Ikarus::operator-(const Eigen::DiagonalMatrix< Scalar, size > &a)
Unary minus for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. a Input DiagonalMatrix. Negation of the DiagonalMatrix.
auto Ikarus::operator+(const Eigen::MatrixBase< Derived > &a, const Eigen::DiagonalWrapper< Derived2 > &b)
Addition of Eigen::Matrix and Eigen::DiagonalWrapper.
Derived Type of the input Eigen matrix. Derived2 Type of the input Eigen DiagonalWrapper. a Input Eigen matrix. b Input Eigen DiagonalWrapper. Sum of Eigen matrix and DiagonalWrapper.
auto Ikarus::operator+(const Eigen::DiagonalWrapper< Derived > &a, const Eigen::MatrixBase< Derived2 > &b)
Addition of Eigen::DiagonalWrapper and Eigen::Matrix.
Derived Type of the input Eigen DiagonalWrapper. Derived2 Type of the input Eigen matrix. a Input Eigen DiagonalWrapper. b Input Eigen matrix. Sum of DiagonalWrapper and Eigen matrix.
std::ostream & Ikarus::operator<<(std::ostream &os, const Eigen::DiagonalMatrix< Scalar, size > &a)
Output stream operator for Eigen::DiagonalMatrix.
Scalar Scalar type. size Size of the diagonal matrix. os Output stream. a Input DiagonalMatrix. Reference to the output stream.
Derived Ikarus::sym(const Eigen::MatrixBase< Derived > &A)
Returns the symmetric part of a matrix.
Derived Type of the input Eigen matrix. A Input Eigen matrix. Symmetric part of the matrix.
Derived Ikarus::skew(const Eigen::MatrixBase< Derived > &A)
Returns the skew part of a matrix.
Derived Type of the input Eigen matrix. A Input Eigen matrix. Skew part of the matrix.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::kgBending.
void Ikarus::printForMaple(const Eigen::EigenBase< Derived > &A)
Method to print the matrix in a format that can directly be copied to Maple.
Derived The derived type of the matrix. A The input matrix.
auto Ikarus::createRandomVector(typename FieldVectorT::value_type lower=-1, typename FieldVectorT::value_type upper=1)
Creates a random vector of the specified type within a given range.
FieldVectorT The type of the vector. lower The lower bound of the random values (default is -1). upper The upper bound of the random values (default is 1). A random vector within the specified range.
Eigen::Matrix< ScalarType, 3, 3 > Ikarus::skew(const Eigen::Vector< ScalarType, 3 > &a)
Create skew 3x3 matrix from 3d vector.
ScalarType The type of the coordinates in the vector. a The vector. The skew matrix.
auto Ikarus::staticCondensation(const Eigen::MatrixBase< Derived > &E, const std::array< size_t, sizeOfCondensedIndices > &indices)
Performs static condensation on a square matrix.
Derived Type of the matrix. sizeOfCondensedIndices Size of the condensed indices. E Input matrix. indices Array of indices to be condensed. Resulting matrix after static condensation. This function performs static condensation on a square matrix. It removes the specified indices from the matrix, computes the remaining submatrices (K11, K12, K22), and returns the result of the static condensation.
Referenced by Ikarus::VanishingStress< stressIndexPair, MI >::tangentModuliImpl.
auto Ikarus::removeCol(const Eigen::MatrixBase< Derived > &E, const std::array< size_t, sizeOfRemovedCols > &indices)
Removes specified columns from a matrix.
Derived Type of the matrix. sizeOfRemovedCols Size of the columns to be removed. E Input matrix. indices Array of column indices to be removed. Resulting matrix after removing specified columns. This function removes specified columns from a matrix. It computes the remaining columns after removing the specified indices and returns the resulting matrix.
Referenced by Ikarus::VanishingStress< stressIndexPair, MI >::stressesImpl, toVoigtAndMaybeReduce.
auto Ikarus::toVoigtAndMaybeReduce(const Eigen::Matrix< ST, 3, 3 > &E, const MaterialImpl &material, bool isStrain=true)
Converts a 3x3 matrix to Voigt notation, possibly reducing it based on material properties.
ST Scalar type of the matrix. MaterialImpl Type of the material implementation. E Input 3x3 matrix. material Reference to the material implementation. isStrain Flag indicating if the matrix represents strain (default is true). Resulting matrix in Voigt notation. This function converts a 3x3 matrix to its Voigt notation. If the material is not reduced, the full Voigt notation is returned. Otherwise, the specified columns (based on material properties, such as VanishingStress) are removed, and the reduced Voigt notation is returned.
decltype(auto) Ikarus::enlargeIfReduced(const Eigen::MatrixBase< Derived > &E)
Enlarges a matrix if it reduced in the context of material laws, i.e., VanishingStress If the material is not reduced the untouched matrix is returned and rendering the function as a NoOp.
M Type of the material. Derived Type of the input matrix. E Input matrix. auto Resulting matrix based on material properties. This function takes an input matrix and, based on the material properties, either returns the original matrix (if it is not reduced) or enlarges the matrix by filling in the specified columns with zeros (if it is reduced).
MessageType & Ikarus::increment(MessageType &e)
Increments the given enum value.
MessageType The enum type. e The enum value to increment. The incremented enum value. Dune::RangeError if trying to increment MessageType::END.
Referenced by Ikarus::IObservable< MessageType >::IObservable.
constexpr T Ikarus::ct_sqrt(T x)
Compile-time square root for integer types.
T The integral type for which square root is calculated. x The value for which square root is calculated. constexpr T The calculated square root.
Referenced by fromVoigt.
auto Ikarus::parameter(Args &&... args)
Creates a Parameter object.
Args The argument types. args The tuple of arguments. auto The Parameter object.
auto Ikarus::functions(Args &&... args)
Creates a Functions object.
Args The argument types. args The tuple of arguments. auto The Functions object.
auto Ikarus::initResults(const Impl::Functions< DerivativeArgs... > &derivativesFunctions, const Impl::Parameter< ParameterArgs... > &parameter)
Initializes the results for functions and parameters.
DerivativeArgs The types of derivative arguments. ParameterArgs The types of parameter arguments. derivativesFunctions The Functions object for derivative arguments. parameter The Parameter object for parameter arguments. auto The initialized results.
auto Ikarus::tensorProductQuadrature(const BaseQuadrature &baseQuad, const Quadrature &onedQuad)
Computes the tensor product quadrature rule using a base and one-dimensional quadrature rule.
This function constructs a tensor product quadrature rule by combining a base quadrature rule and a one-dimensional quadrature rule. It iterates over the points of the base quadrature and combines them with each point of the one-dimensional quadrature. BaseQuadrature Type of the base quadrature. Quadrature Type of the one-dimensional quadrature. baseQuad The base quadrature rule. onedQuad The one-dimensional quadrature rule. Dune::QuadratureRule<double, BaseQuadrature::d + 1> - Tensor product quadrature rule.
Eigen::Tensor< typename Derived::Scalar, rank > Ikarus::tensorView(const Eigen::EigenBase< Derived > &matrix, const std::array< T, rank > &dims)
View an Eigen matrix as an Eigen Tensor with specified dimensions.
Derived Type of the input Eigen matrix. T Type of the elements in the matrix. rank Rank of the resulting Tensor. matrix Input Eigen matrix to be cast. dims Dimensions of the resulting Tensor. Eigen::Tensor<typename Derived::Scalar, rank> The casted Eigen Tensor.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::materialTangent, Ikarus::NeoHookeT< ST >::tangentModuliImpl.
auto Ikarus::dyadic(const auto &A_ij, const auto &B_kl)
Computes the dyadic product of two Eigen tensors.
The components of the result read \[ \CI_{ijkl} = A_{ij}B_{kl}. \] A_ij First tensor. B_kl Second tensor. Resulting tensor after the dyadic product.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::materialTangent, Ikarus::NeoHookeT< ST >::tangentModuliImpl.
auto Ikarus::symmetricIdentityFourthOrder()
Generates a symmetric identity fourth-order tensor.
ScalarType Type of the elements in the tensor. dim Dimension of the tensor. Symmetric identity fourth-order tensor.
Referenced by Ikarus::StVenantKirchhoffT< ST >::tangentModuliImpl.
auto Ikarus::symmetricFourthOrder(const auto &A, const auto &B)
Generates a symmetric fourth-order tensor based on two second-order input tensors.
The components of the result read \[ \CI_{ijkl} = \frac{1}{2} \left(A_{ik}B_{jl}+A_{il}B_{jk} \right) . \] ScalarType Type of the elements in the tensors. dim Dimension of the tensors. A First tensor. B Second tensor. Symmetric fourth-order tensor.
auto Ikarus::identityFourthOrder()
Generates an identity fourth-order tensor.
The components of the result read \[ \CI_{ijkl} = \de_{ij}\de_{kl}. \] ScalarType Type of the elements in the tensor. dim Dimension of the tensor. Identity fourth-order tensor.
Referenced by Ikarus::StVenantKirchhoffT< ST >::tangentModuliImpl.
auto Ikarus::fourthOrderIKJL(const Eigen::MatrixBase< AType > &A, const Eigen::MatrixBase< BType > &B)
Computes the IKJL product of two matrices.
The components of the result read \[ \CI_{ijkl} = A_{ik}B_{jl}, \] which simply swaps the inner slots jand k AType Type of the first matrix. BType Type of the second matrix. A First matrix. B Second matrix. Resulting tensor of the IKJL product.
Referenced by Ikarus::NeoHookeT< ST >::tangentModuliImpl.
auto Ikarus::symTwoSlots(const Eigen::TensorFixedSize< ScalarType, Eigen::Sizes< dim, dim, dim, dim > > &t, const std::array< size_t, 2 > &slots)
Creates a symmetric fourth-order tensor in the two specified slots of the input tensor.
ScalarType Type of the elements in the tensor. t Input tensor. slots Indices of the slots to be swapped. Fourth-order Tensor which is symmetric in the given slots.
Referenced by Ikarus::NeoHookeT< ST >::tangentModuliImpl.
constexpr Eigen::Index Ikarus::toVoigt(Eigen::Index i, Eigen::Index j) noexcept
Converts 2D indices to Voigt notation index.
i Row index. j Column index. Eigen::Index Voigt notation index. This function converts 2D indices (i, j) to a Voigt notation index. The Voigt notation is used to represent the six unique components of a symmetric 3x3 matrix in a one-dimensional array. If the input indices are not within the valid range (0, 1, 2), an assertion failure is triggered.
Referenced by Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateAt, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::computeMaterialAndStrains, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::materialTangent, Ikarus::Material< MI >::storedEnergy, Ikarus::Material< MI >::stresses, Ikarus::Material< MI >::tangentModuli, toVoigt, toVoigtAndMaybeReduce.
Eigen::Matrix< ScalarType, 6, 6 > Ikarus::toVoigt(const Eigen::TensorFixedSize< ScalarType, Eigen::Sizes< 3, 3, 3, 3 > > &ft)
Converts a fourth-order tensor of fixed size 3x3x3x3 to a Voigt notation matrix of size 6x6.
ScalarType Data type of the tensor elements. ft Fourth-order tensor . Voigt notation matrix. This function converts a fourth-order tensor to a Voigt notation matrix, which is a symmetric 6x6 matrix containing the unique components of the input tensor. The mapping from the tensor indices to the Voigt notation indices is performed by the toVoigt function. The current implementation does not take advantage of this symmetry.
auto Ikarus::toVoigt(const Eigen::Matrix< ST, size, size, Options, size, size > &E, bool isStrain=true)
Converts a square 2x2 or 3x3 matrix to a Voigt notation vector.
ST Data type of the matrix elements. size Number of rows and columns of the square matrix. Options Eigen matrix options. E Input matrix of size (size x size). isStrain Flag indicating whether the conversion is for strain (true) or not (false). Vector with components in Voigt notation vector. This function converts a square matrix to a Voigt notation vector, which contains the unique components of the input matrix. The mapping from the matrix indices to the Voigt notation indices is performed by the toVoigt function. The optional isStrain parameter allows the user to specify whether the conversion is intended for strain calculations. If isStrain is true, the off-diagonal components are multiplied by 2, providing the correct Voigt notation for symmetric strain tensors.
auto Ikarus::fromVoigt(const Eigen::Vector< ST, size > &EVoigt, bool isStrain=true)
Converts a vector given in Voigt notation to a matrix.
ST Scalar type of the vector elements. size Size of the Voigt notation vector. EVoigt Voigt notation vector. isStrain Flag indicating whether the vector represents a strain (default is true). Matrix corresponding to the vector in Voigt notation. This function converts a vector given in Voigt notation to the corresponding matrix. The conversion depends on the size The parameter isStrain is used to determine the conversion factor for off-diagonal components, which need to be divided by 2 in the matrix representation if the quantity is a strain tensor. The function requires that the size of the Voigt notation vector is valid (1, 3, or 6).
Referenced by fromVoigt, Ikarus::VanishingStress< stressIndexPair, MI >::stressesImpl, Ikarus::VanishingStress< stressIndexPair, MI >::tangentModuliImpl.
constexpr std::array< size_t, 2 > Ikarus::fromVoigt(size_t i)
Converts a Voigt notation index to matrix indices.
i Voigt notation index. Matrix indices corresponding to the Voigt notation index. This function converts a Voigt notation index to the corresponding matrix indices. The mapping is based on the assumption that the Voigt notation indices 0, 1, and 2 represent the diagonal components 00, 11, and 22, respectively. The remaining Voigt notation indices (3, 4, and 5) correspond to the off-diagonal components (12 and 21, 02 and 20, 01 and 10). The function asserts that the input index is within the valid range for Voigt notation (0 to 5).
auto Ikarus::fromVoigt(const Eigen::Matrix< ScalarType, 6, 6 > &CVoigt)
Converts a matrix in Voigt notation to a Fourth-order tensor.
ScalarType Scalar type of the matrix elements. CVoigt Voigt notation matrix. Fourth-order tensor corresponding to the matrix in Voigt notation. This function converts a Voigt notation matrix to the corresponding 4th-order tensor. The function uses the fromVoigt function to map matrix indices to tensor indices. The resulting tensor is symmetric due to symmetry considerations.
Eigen::Matrix3d Ikarus::calcTransformationMatrix2D(const Geometry &geometry)
Calculates the 2D transformation matrix.
This function computes the transformation matrix needed to transform second-order tensors represented in Voigt notation from local to global coordinate system for 2D elements. Geometry The geometry type. geometry Reference to the geometry object. The transformation matrix for 2D elements.
Eigen::Matrix< double, 6, 6 > Ikarus::calcTransformationMatrix3D(const Geometry &geometry)
Calculates the 3D transformation matrix.
This function computes the transformation matrix needed to transform second-order tensors represented in Voigt notation from local to global coordinate system for 3D elements. Geometry The geometry type. geometry Reference to the geometry object. The transformation matrix for 3D elements.