ikarus::finite_elements
def ikarus.finite_elements.volumeLoad(f, d)
Referenced by ikarus.finite_elements.volumeLoad2D, ikarus.finite_elements.volumeLoad3D.
def ikarus.finite_elements.volumeLoad2D(f)
def ikarus.finite_elements.volumeLoad3D(f)
def ikarus.finite_elements.neumannBoundaryLoad(boundaryPatch, f)
def ikarus.finite_elements.registerPreElement(name, includes, element_type, *args)
Referenced by ikarus.finite_elements.eas, ikarus.finite_elements.kirchhoffLoveShell, ikarus.finite_elements.linearElastic, ikarus.finite_elements.nonLinearElastic.
def ikarus.finite_elements.nonLinearElastic(mat)
def ikarus.finite_elements.linearElastic(youngs_modulus, nu)
def ikarus.finite_elements.eas(numberofparameters)
def ikarus.finite_elements.kirchhoffLoveShell(youngs_modulus, nu, thickness)
def ikarus.finite_elements.makeFE(basis, *skills)