ikarus::basis
def ikarus.basis.basis(gv, tree)
Referenced by Ikarus::Python::registerDirichletValues, Ikarus::Python::registerElement, Ikarus::Python::registerKirchhoffLoveShell, Ikarus::Python::registerNonLinearElastic.