ikarus::dirichlet_values
def ikarus.dirichlet_values.__fixBoundaryDOFs(dirichletValues)
def ikarus.dirichlet_values.dirichletValues(basis)
@brief Creates a Dirichlet values handler for the given basis. @param basis: The basis. @return: The created Dirichlet values handler.
Referenced by Ikarus::makeDenseFlatAssembler, Ikarus::makeSparseFlatAssembler, Ikarus::Python::registerFlatAssembler.