Ikarus::Python
void Ikarus::Python::registerSparseFlatAssembler(pybind11::handle scope, pybind11::class_< Assembler, options... > cls)
Register Python bindings for a SparseFlatAssembler class. .
This function registers Python bindings for a SparseFlatAssembler class, allowing it to be used in Python scripts. This function is a result of the macro MAKE_ASSEMBLER_REGISTERY_FUNCTION( SparseFlatAssembler ). The registered class will have an initializer that takes a list of finite elements (fes) and a DirichletValuesType object. It exposes several member functions to Python: getMatrix(req): Returns a dense matrix based on the specified FERequirementType. getReducedMatrix(req): Returns a reduced dense matrix based on the specified FERequirementType. getVector(req): Returns a vector based on the specified FERequirementType. getScalar(req): Returns a scalar based on the specified FERequirementType. getReducedVector(req): Returns a reduced vector based on the specified FERequirementType. createFullVector(redVec): Creates a full vector from a reduced vector. reducedSize(): Returns the size of the reduced space. Assembler The SparseFlatAssembler class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the SparseFlatAssembler class. <>
void Ikarus::Python::registerDenseFlatAssembler(pybind11::handle scope, pybind11::class_< Assembler, options... > cls)
Register Python bindings for a DenseFlatAssembler class. .
This function registers Python bindings for a DenseFlatAssembler class, allowing it to be used in Python scripts. This function is a result of the macro MAKE_ASSEMBLER_REGISTERY_FUNCTION( DenseFlatAssembler ). The registered class will have an initializer that takes a list of finite elements (fes) and a DirichletValuesType object. It exposes several member functions to Python: getMatrix(req): Returns a dense matrix based on the specified FERequirementType. getReducedMatrix(req): Returns a reduced dense matrix based on the specified FERequirementType. getVector(req): Returns a vector based on the specified FERequirementType. getScalar(req): Returns a scalar based on the specified FERequirementType. getReducedVector(req): Returns a reduced vector based on the specified FERequirementType. createFullVector(redVec): Creates a full vector from a reduced vector. reducedSize(): Returns the size of the reduced space. Assembler The DenseFlatAssembler class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the DenseFlatAssembler class. <>
void Ikarus::Python::registerBasisHandler(pybind11::handle scope, pybind11::class_< BasisHandler, options... > cls)
Register a Python wrapper for an Ikarus basis class.
BasisHandler The Ikarus handler basis class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the Ikarus basis handler class.
void Ikarus::Python::registerDirichletValues(pybind11::handle scope, pybind11::class_< DirichletValues, options... > cls)
Register Python bindings for a DirichletValues class.
This function registers Python bindings for a DirichletValues class, allowing it to be used in Python scripts. The registered class will have an initializer that takes a Basis object. It exposes several member functions to Python: fixBoundaryDOFs(f): Fixes boundary degrees of freedom using a user-defined function f. fixBoundaryDOFsUsingLocalView(f): Fixes boundary degrees of freedom using a user-defined function f with a LocalView argument. fixBoundaryDOFsUsingLocalViewAndIntersection(f): Fixes boundary degrees of freedom using a user-defined function f with LocalView and Intersection arguments. fixDOFs(f): Fixes boundary degrees of freedom using a user-defined function f with the boolean vector and the basis as arguments. DirichletValues The DirichletValues class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the DirichletValues class.
void Ikarus::Python::registerKirchhoffLoveShell(pybind11::handle scope, pybind11::class_< KirchhoffLoveShell, options... > cls)
Register Python bindings for a KirchhoffLoveShell class.
This function registers Python bindings for a KirchhoffLoveShell class, allowing it to be used in Python scripts. The registered class will have several initializers with different sets of parameters. KirchhoffLoveShell The KirchhoffLoveShell class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the KirchhoffLoveShell class.
void Ikarus::Python::registerLinearElastic(pybind11::handle scope, pybind11::class_< LinearElastic, options... > cls)
Register Python bindings for a Linear Elastic class.
This function registers Python bindings for a LinearElastic class, allowing it to be used in Python scripts. The registered class will have several initializers with different sets of parameters. LinearElastic The LinearElastic class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the LinearElastic class.
Ikarus::Python::MAKE_MATERIAL_REGISTERY_FUNCTION(LinearElasticity, 6)
Ikarus::Python::MAKE_MATERIAL_REGISTERY_FUNCTION(StVenantKirchhoff, 6)
Ikarus::Python::MAKE_MATERIAL_REGISTERY_FUNCTION(NeoHooke, 6)
void Ikarus::Python::registerNonLinearElastic(pybind11::handle scope, pybind11::class_< NonLinearElastic, options... > cls)
void Ikarus::Python::registerElement(pybind11::handle scope, pybind11::class_< FE, options... > cls)
Register Python bindings for a generic finite element class.
This function registers Python bindings for a generic finite element class, allowing it to be used in Python scripts. The registered class will have multiple initializers with different sets of parameters and member functions to calculate results and access properties. defaultInitializers If true, include default initializers for the finite element class. FE The generic finite element class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the finite element class.
Referenced by registerKirchhoffLoveShell, registerLinearElastic.
void Ikarus::Python::registerCalculateAt(pybind11::handle scope, pybind11::class_< FE, options... > cls, auto restultTypesTuple)
Referenced by registerLinearElastic, registerNonLinearElastic.
auto Ikarus::Python::makeRT()
void Ikarus::Python::registerBoundaryPatch(pybind11::handle scope, pybind11::class_< BoundaryPatch, options... > cls)