Ikarus::Materials
using Ikarus::Materials::ArrudaBoyce = typedef ArrudaBoyceT<double>
Alias for ArrudaBoyceT with double as the default scalar type.
using Ikarus::Materials::BlatzKo = typedef BlatzKoT<double>
Alias for BlatzKoT with double as the default scalar type.
using Ikarus::Materials::Gent = typedef GentT<double>
Alias for GentT with double as the default scalar type.
using Ikarus::Materials::InvariantBased = typedef InvariantBasedT<double, n>
Alias for InvariantBasedT with double as the default scalar type.
using Ikarus::Materials::Ogden = typedef OgdenT<double, n, tag>
Alias for OgdenT with double as the default scalar type.
using Ikarus::Materials::NeoHooke = typedef NeoHookeT<double>
Alias for NeoHookeT with double as the default scalar type.
using Ikarus::Materials::NoVolumetricPart = typedef Volumetric<VF0>
using Ikarus::Materials::LinearElasticity = typedef LinearElasticityT<double>
Convenience typedef for LinearElasticity with double as ScalarType.
using Ikarus::Materials::StVenantKirchhoff = typedef StVenantKirchhoffT<double>
Alias for StVenantKirchhoffT with double as the default scalar type.
auto Ikarus::Materials::makeBlatzKo(double mu)
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Blatz-Ko model.
mu The shear modulus. A hyperelastic material model.
auto Ikarus::Materials::makeOgden(const typename Ogden< n, tag >::MaterialParameters &mu, const typename Ogden< n, tag >::MaterialExponents alpha, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Ogden model.
n Number of Ogden material parameters. PrincipalStretchTags Type of the principal stretches, either total or deviatoric. VolumetricFunction Type of the volumetric function. mu The shear parameters (mu_i). alpha The (exponential) parameters (alpha_i). K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
auto Ikarus::Materials::makeInvariantBased(const typename InvariantBased< n >::MaterialParameters &mu, const typename InvariantBased< n >::Exponents pex, const typename InvariantBased< n >::Exponents qex, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the general invariant-based model.
n Number of material parameters. VolumetricFunction Type of the volumetric function. mu The shear parameters (mu_i). pex The exponents related to the first invariant. qex The exponents related to the second invariant. K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
auto Ikarus::Materials::makeMooneyRivlin(const typename InvariantBased< 2 >::MaterialParameters &mu, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Mooney-Rivlin model (InvariantBased model with n = 2).
VolumetricFunction Type of the volumetric function. mu The shear parameters (mu_i). K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
auto Ikarus::Materials::makeYeoh(const typename InvariantBased< 3 >::MaterialParameters &mu, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Yeoh model (InvariantBased model with n = 3).
VolumetricFunction Type of the volumetric function. mu The shear parameters (mu_i). K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
auto Ikarus::Materials::makeArrudaBoyce(const ArrudaBoyceMatParameters &matPar, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Arruda-Boyce model.
VolumetricFunction Type of the volumetric function. matPar The Arruda-Boyce material parameters (C and lambdaM). K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
auto Ikarus::Materials::makeGent(const GentMatParameters &matPar, double K=0.0, const VolumetricFunction &vf=VolumetricFunction{})
A helper function to create a hyperelastic material model, where the deviatoric part is according to the Gent model.
VolumetricFunction Type of the volumetric function. matPar The Gent material parameters (mu and Jm). K Bulk modulus (or) Lamé's first parameter. vf The volumetric function. A hyperelastic material model.
consteval bool Ikarus::Materials::hasCorrectSize()
Template function for checking if the strain size is correct.
The given strain quantity has to be a Eigen::Vector6 or a Eigen::Matrix3 MAT Type of the material. S Type of the strains.
auto Ikarus::Materials::makeVanishingStrain(MaterialImpl mat)
Factory function to create a VanishingStrain material with specified strain indices.
matrixIndexPair The array of MatrixIndexPair representing fixed strain components. MaterialImpl The underlying material model. mat The underlying material model. p_tol Tolerance for stress reduction. VanishingStress The created VanishingStress material.
Referenced by planeStrain.
auto Ikarus::Materials::planeStrain(const MaterialImpl &mat)
Factory function to create a VanishingStrain material for plane strain conditions.
The output is as follows for the stress and material tangent (in Voigt notation): \[ \BS(\BE) \rightarrow \begin{bmatrix} S_{11} \\ S_{22} \\ S_{12} \end{bmatrix}, \quad \BBC(\BE) \rightarrow \begin{bmatrix} C_{11} & C_{12} & C_{13} \\ C_{21} & C_{22} & C_{23} \\ C_{31} & C_{32} & C_{33} \end{bmatrix} \] MaterialImpl The underlying material model. mat The underlying material model. VanishingStrain The created VanishingStrain material for plane strain case.
auto Ikarus::Materials::makeVanishingStress(MaterialImpl mat, typename MaterialImpl::ScalarType p_tol=1e-12)
Factory function to create a VanishingStress material with specified stress indices.
matrixIndexPair The array of MatrixIndexPair representing fixed stress components. MaterialImpl The underlying material model. mat The underlying material model. p_tol Tolerance for stress reduction. VanishingStress The created VanishingStress material.
Referenced by beamMaterial, planeStress, shellMaterial.
auto Ikarus::Materials::planeStress(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for plane stress conditions.
MaterialImpl The underlying material model. mat The underlying material model. tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.
auto Ikarus::Materials::shellMaterial(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for a shell material with zero normal stress condition.
MaterialImpl The underlying material model. mat The underlying material model. tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.
auto Ikarus::Materials::beamMaterial(const MaterialImpl &mat, typename MaterialImpl::ScalarType tol=1e-8)
Factory function to create a VanishingStress material for a beam material with two zero normal stress condition.
MaterialImpl The underlying material model. mat The underlying material model. p_tol Tolerance for stress reduction. VanishingStress The created VanishingStress material for plane stress.