Ikarus::Python
void Ikarus::Python::registerFlatAssembler(pybind11::handle scope, pybind11::class_< Assembler, options... > cls)
Register Python bindings for a assembler class. .
The registered class will have an initializer that takes a list of finite elements (fes) and a DirichletValuesType object. It exposes several member functions to Python: matrix(req): Returns a dense matrix based on the specified FERequirementType. vector(req,affordance,dbcOption): Returns a vector based on the specified FERequirementType. scalar(req,affordance): Returns a scalar based on the specified FERequirementType. createFullVector(redVec): Creates a full vector from a reduced vector. reducedSize(): Returns the size of the reduced space. Assembler The assembler class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the assembler class.
Referenced by registerAssemblerManipulator.
void Ikarus::Python::registerSparseFlatAssembler(pybind11::handle scope, pybind11::class_< Assembler, options... > cls)
void Ikarus::Python::registerDenseFlatAssembler(pybind11::handle scope, pybind11::class_< Assembler, options... > cls)
void Ikarus::Python::registerSparseMatrixWrapper(pybind11::handle scope)
void Ikarus::Python::registerAssemblerManipulator(pybind11::handle scope, pybind11::class_< AssemblerManipulator, options... > cls)
void Ikarus::Python::registerBasisHandler(pybind11::handle scope, pybind11::class_< BasisHandler, options... > cls)
Register a Python wrapper for an Ikarus basis class.
BasisHandler The Ikarus handler basis class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the Ikarus basis handler class.
void Ikarus::Python::forwardCorrectFunction(DirichletValues &dirichletValues, const pybind11::function &functor, auto &&cppFunction)
void Ikarus::Python::registerDirichletValues(pybind11::handle scope, pybind11::class_< DirichletValues, options... > cls)
Register Python bindings for a DirichletValues class.
This function registers Python bindings for a DirichletValues class, allowing it to be used in Python scripts. The registered class will have an initializer that takes a Basis object. It exposes several member functions to Python: fixBoundaryDOFs(f): Fixes boundary degrees of freedom using a user-defined function f than can be called with the following arguments: with the boolean vector and the global index. with the boolean vector, the local index and the LocalView. with the boolean vector, the local index, the LocalView and the Intersection. fixDOFs(f): Fixes boundary degrees of freedom using a user-defined function f with the basis and the boolean vector as arguments. setSingleDOF(i, flag: bool): Fixes or unfixes DOF with index i -isConstrained(i): Checks whether index i is constrained -reset()`: Resets the whole container The following properties can be accessed: container: the underlying container of dirichlet flags (as a const reference) size: the size of the underlying basis fixedDOFsize: the amount of DOFs currently fixed DirichletValues The DirichletValues class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the DirichletValues class.
void Ikarus::Python::registerCalculateAt(pybind11::handle scope, pybind11::class_< FE, options... > cls, auto resultTypesTuple)
Registers the calculateAt method for a finite element class in Python.
This function is used to expose the calculateAt method of a finite element class to Python using Pybind11. FE The finite element class type. options Variadic template parameters for additional options when defining the Python class. scope The Pybind11 handle to the Python module or class where the method will be registered. cls The Pybind11 class wrapper for the finite element class. restultTypesTuple A tuple containing the result types to be supported by the calculateAt method. The calculateAt method is exposed to Python, allowing users to compute element values at a specific location. Example usage in Python: fe_instance=MyFiniteElementClass() result=fe_instance.calculateAt(feRequirements,local,"linearStress") feRequirements The requirements for the finite element calculation. local The local coordinates where the calculation is performed. resultType A string specifying the desired result type for the calculation. The calculated result as a EigenType but NumPy array. Dune::NotImplemented If the specified resultType is not supported by the finite element.
Referenced by registerFE.
void Ikarus::Python::registerFE(pybind11::handle scope, pybind11::class_< FE, options... > cls)
Register Python bindings for the FE class.
This function registers Python bindings for a FE class, allowing it to be used in Python scripts. FE The FE class to be registered. options Variadic template parameters for additional options when defining the Python class. scope A Pybind11 handle representing the Python scope where the class should be registered. cls The Pybind11 class template to be used for registering the KirchhoffLoveShell class.
void Ikarus::Python::registerMaterial(pybind11::handle scope, pybind11::class_< Material, options... > cls)
Ikarus::Python::MAKE_MATERIAL_REGISTRY_FUNCTION(LinearElasticity, 6)
Ikarus::Python::MAKE_MATERIAL_REGISTRY_FUNCTION(StVenantKirchhoff, 6)
Ikarus::Python::MAKE_MATERIAL_REGISTRY_FUNCTION(NeoHooke, 6)
void Ikarus::Python::registerFERequirement(pybind11::handle scope, pybind11::class_< FE, options... > cls)
Referenced by registerFE.
void Ikarus::Python::registerNonLinearElasticPre(pybind11::handle scope, pybind11::class_< NonLinearElasticPre, options... > cls)
Registers a NonLinearElasticPre class in Python.
NonLinearElasticPre The NonLinearElasticPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerLinearElasticPre(pybind11::handle scope, pybind11::class_< LinearElasticPre, options... > cls)
Registers a LinearElasticPre class in Python.
LinearElasticPre The LinearElasticPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerTrussPre(pybind11::handle scope, pybind11::class_< TrussPre, options... > cls)
Registers a TrussPre class in Python.
TrussPre The TrussPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerKirchhoffLoveShellPre(pybind11::handle scope, pybind11::class_< KirchhoffLoveShellPre, options... > cls)
Registers a KirchhoffLoveShellPre class in Python.
KirchhoffLoveShellPre The KirchhoffLoveShellPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerEnhancedAssumedStrainsPre(pybind11::handle scope, pybind11::class_< EASPre, options... > cls)
Registers an EnhancedAssumedStrainsPre class in Python.
EASPre The EnhancedAssumedStrainsPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerNeumannBoundaryLoadPre(pybind11::handle scope, pybind11::class_< NeumannBoundaryLoadPre, options... > cls)
Registers a NeumannBoundaryLoadPre class in Python.
NeumannBoundaryLoadPre The NeumannBoundaryLoadPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerVolumeLoadPre(pybind11::handle scope, pybind11::class_< VolumeLoadPre, options... > cls)
Registers a VolumeLoadPre class in Python.
VolumeLoadPre The VolumeLoadPre class. options Additional options for the pybind11 class. scope Python handle to the module or class scope. cls The pybind11 class to register.
void Ikarus::Python::registerVtkWriter(pybind11::handle scope, pybind11::class_< Writer, options... > cls)
Register Python bindings for a VtkWriter class. .
The registered VtkWriter class provides functionalities for writing VTK files from assembled data. This class supports adding result data as cell or point data and configuring VTK output formats. This function registers the following methods for the VtkWriter class: addAllResults(dataTag: DataTag) addResult(resType: str, dataTag: ikarus.io.DataTag) write(fileName), returns actual fileName addInterpolation(writer, vals_::np.array, basis, name: str, dataTag: ikarus.io.DataTag) addPointData() (multiple overloads) addCellData() (multiple overloads) setFormat(type: dune.vtk.FormatTypes) setDatatype(type: dune.vtk.DataTypes) setHeadertype(type: dune.vtk.DataTypes) Writer The writer class type. options Additional options for the writer class. scope The scope in which to register the class. cls The class object to register the methods with.
void Ikarus::Python::registerBoundaryPatch(pybind11::handle scope, pybind11::class_< BoundaryPatch, options... > cls)