Ikarus::FEHelper
auto Ikarus::FEHelper::localSolutionBlockVector(const Vector &x, const typename Traits::LocalView &localView, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt)
Gets the local solution Dune block vector.
Traits Type of the FE traits. ST Scalar type for the local solution vector. Vector Global solution vector x The global solution vector. localView Local view of the element. dx Optional global solution vector. A Dune block vector representing the solution quantities at each node.
void Ikarus::FEHelper::globalIndicesFromLocalView(const LocalView &localView, std::vector< typename LocalView::MultiIndex > &globalIndices)
Get the global indices for the provided local view of an element.
LocalView Type of the local view localView Local view of the element. globalIndices Output vector to store global indices.
Referenced by globalIndices.
void Ikarus::FEHelper::globalIndices(const FiniteElement &fe, std::vector< typename FiniteElement::LocalView::MultiIndex > &globalIndices)
Get the global indices for the provided finite element.
The global indices are collected in a FlatInterLeaved order or in BlockedInterleaved order. This function can handle a scalar basis, power basis, and a composite basis. FiniteElement Type of the finite element. fe The finite element. globalIndices Output vector to store global indices.
Referenced by Ikarus::VectorFlatAssembler< FEC, DV >::assembleRawVectorImpl, Ikarus::SparseFlatAssembler< FEC, DV >::getReducedMatrixImpl, Ikarus::DenseFlatAssembler< FEC, DV >::getReducedMatrixImpl, Ikarus::VectorFlatAssembler< FEC, DV >::getReducedVectorImpl, Ikarus::utils::globalIndexFromGlobalPosition, globalIndices, globalIndicesFromLocalView.