ikarus::basis
def ikarus.basis.basis(gv, tree)
@brief Creates a basis handler for the given grid view and tree. @param gv: The grid view. @param tree: The tree of pre basis types. @return: The created basis handler.
Referenced by Ikarus::Vtk::Writer< AS, DC, Base >::addInterpolation, Ikarus::utils::globalIndexFromGlobalPosition, Ikarus::Python::registerDirichletValues.