Ikarus::KirchhoffLoveShell
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::Traits = FETraits<B, FER, useEigenRef>
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::Basis = typename Traits::Basis
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::FlatBasis = typename Traits::FlatBasis
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::FERequirementType = typename Traits::FERequirementType
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::LocalView = typename Traits::LocalView
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::Geometry = typename Traits::Geometry
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::GridView = typename Traits::GridView
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::Element = typename Traits::Element
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::BasePowerFE = PowerBasisFE<Basis>
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::VolumeType = Volume<KirchhoffLoveShell, Traits>
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::TractionType = Traction<KirchhoffLoveShell, Traits>
using Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::PowerBasisFE< B >::GlobalIndex = typename Traits::GlobalIndex
Type of the global index.
using Ikarus::PowerBasisFE< B >::GridElement = typename Traits::Element
Type of the grid element.
constexpr int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::myDim
constexpr int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::worldDim
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl.
constexpr int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::membraneStrainSize
constexpr int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::bendingStrainSize
constexpr int Ikarus::PowerBasisFE< B >::num_children
Number of children in the powerBasis.
Referenced by Ikarus::PowerBasisFE< B >::globalFlatIndices.
std::shared_ptr<const Geometry> Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::localBasis_
DefaultMembraneStrain Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::membraneStrain_
double Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::emod_
double Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::nu_
double Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::thickness_
size_t Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::numberOfNodes_
int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::order_
Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::KirchhoffLoveShell(const Basis &globalBasis, const typename LocalView::Element &element, double emod, double nu, double thickness, VolumeLoad volumeLoad={}, const BoundaryPatch< GridView > *neumannBoundary=nullptr, NeumannBoundaryLoad neumannBoundaryLoad={})
Constructor for the KirchhoffLoveShell class.
Initializes the KirchhoffLoveShell instance with the given parameters. VolumeLoad The type representing the volume load function. NeumannBoundaryLoad The type representing the Neumann boundary load function. globalBasis The global basis for the finite element. element The local element to bind. emod Young's modulus of the material. nu Poisson's ratio of the material. thickness Thickness of the shell. volumeLoad The volume load function (optional, default is utils::LoadDefault). neumannBoundary The Neumann boundary patch (optional, default is nullptr). neumannBoundaryLoad The Neumann boundary load function (optional, default is LoadDefault).
auto Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
Get the displacement function and nodal displacements.
Retrieves the displacement function and nodal displacements based on the given FERequirements. ST The scalar type used for calculations. par The FERequirements. dx Optional additional displacement vector. The displacement function.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateVectorImpl.
const Geometry & Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::geometry() const
size_t Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::numberOfNodes() const
int Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::order() const
double Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ST The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ST The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateAt(const FERequirementType &req, const Dune::FieldVector< double, Traits::mydim > &local) const
Calculates a requested result at a specific local position.
req The FERequirementType object holding the global solution. local Local position vector. calculated result resType The type representing the requested result.
constexpr size_t Ikarus::PowerBasisFE< B >::size() const
Get the size of the local view.
The size of the local view.
void Ikarus::PowerBasisFE< B >::globalFlatIndices(std::vector< GlobalIndex > &globalIndices) const
Get the global flat indices for the power basis.
The global indices are collected in a FlatInterLeaved order. I.e. x_0, y_0, z_0, ..., x_n, y_n, z_n globalIndices Output vector to store global indices.
const GridElement & Ikarus::PowerBasisFE< B >::gridElement() const
Get the grid element associated with the local view.
The grid element.
Referenced by Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateAt, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateMatrix, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateVectorImpl, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateVectorImpl.
const LocalView & Ikarus::PowerBasisFE< B >::localView() const
Get the const reference to the local view.
The const reference to the local view.
Referenced by Ikarus::LinearElastic< B, FER, useEigenRef >::displacementFunction, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::displacementFunction, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::displacementFunction.
LocalView & Ikarus::PowerBasisFE< B >::localView()
Get the reference to the local view.
The reference to the local view.
double Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
double Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::computeMaterialAndStrains(const Dune::FieldVector< double, 2 > &gpPos, int gpIndex, const Geometry &geo, const auto &uFunction) const
Compute material properties and strains at a given integration point.
gpPos The position of the integration point. gpIndex The index of the integration point. geo The geometry object providing position and derivatives. uFunction The function representing the displacement field. gpPos The type of the integration point position. gpIndex The type of the integration point index. geo The type of the geometry object. uFunction The type of the displacement field function. A tuple containing the material tangent, membrane strain, bending, Jacobian matrix of the reference position, Jacobian matrix of the current position, Hessian matrix of the current position, Hessian matrix of the reference position, normal vector, and normalized normal vector at the given integration point.
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateVectorImpl.
void Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType< ST > K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
void Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
auto Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
Eigen::Matrix< ST, 3, 3 > Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::kgBending(const Eigen::Matrix< ST, 2, 3 > &jcur, const Eigen::Matrix3< ST > &h, const auto &dN, const auto &ddN, const Eigen::Vector3< ST > &a3N, const Eigen::Vector3< ST > &a3, const Eigen::Vector3< ST > &S, int I, int J) const
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl.
Eigen::Matrix< ST, 3, 3 > Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::bopBending(const Eigen::Matrix< ST, 2, 3 > &jcur, const Eigen::Matrix3< ST > &h, const auto &dN, const auto &ddN, const int node, const Eigen::Vector3< ST > &a3N, const Eigen::Vector3< ST > &a3) const
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::calculateVectorImpl.
Eigen::Matrix< double, 3, 3 > Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::materialTangent(const Eigen::Matrix< double, 3, 3 > &Aconv) const
Referenced by Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::computeMaterialAndStrains.
auto Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
void Ikarus::Volume< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
auto Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > dx=std::nullopt) const
void Ikarus::Traction< KirchhoffLoveShell< B, FERequirements<>, false > , FETraits< B, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const