Ikarus::ScalarFlatAssembler
using Ikarus::ScalarFlatAssembler< FEC, DV >::Base = FlatAssemblerBase<FEC, DV>
Type alias for the base class.
friend Ikarus::ScalarFlatAssembler< FEC, DV >::ScalarAssembler< ScalarFlatAssembler, FEC, DV, double >
ScalarType Ikarus::ScalarFlatAssembler< FEC, DV >::scal_
ScalarFlatAssembler< B, FEC >::ScalarType & Ikarus::ScalarFlatAssembler< B, FEC >::getScalarImpl(const FERequirement &feRequirements, ScalarAffordance affordance)
using Ikarus::FlatAssemblerBase< FEC, DV >::Basis = typename DV::Basis
Type of the basis.
using Ikarus::FlatAssemblerBase< FEC, DV >::DirichletValuesType = DV
Type of the Dirichlet values.
using Ikarus::FlatAssemblerBase< FEC, DV >::FEContainer = FEC
Type of the finite element container (reference or by value).
using Ikarus::FlatAssemblerBase< FEC, DV >::FERequirement = typename FEContainerRaw::value_type::Requirement
Type of the finite element requirement.
using Ikarus::FlatAssemblerBase< FEC, DV >::GlobalIndex = typename FEContainerRaw::value_type::GlobalIndex
Type of the global index.
using Ikarus::ScalarAssembler< ScalarFlatAssembler< FEC, DV > , FEC, DV, double >::ScalarAssemblerType = ScalarFlatAssembler< FEC, DV >
using Ikarus::ScalarAssembler< ScalarFlatAssembler< FEC, DV > , FEC, DV, double >::ScalarType = double
using Ikarus::ScalarAssembler< ScalarFlatAssembler< FEC, DV > , FEC, DV, double >::FEContainerRaw = std::remove_cvref_t<FEC>
Type of the raw finite element container.
using Ikarus::FlatAssemblerBase< FEC, DV >::FEContainerRaw = std::remove_cvref_t<FEC>
Type of the raw finite element container.
using Ikarus::FlatAssemblerBase< FEC, DV >::GridView = typename Basis::GridView
Type of the grid view.
using Ikarus::FlatAssemblerBase< FEC, DV >::SizeType = typename DirichletValuesType::SizeType
size_type of the container storing Dirichlet flags
using Ikarus::FlatAssemblerBase< FEC, DV >::AffordanceCollectionType = AffordanceCollection<ScalarAffordance, VectorAffordance, MatrixAffordance>
const ScalarType & Ikarus::ScalarAssembler< ScalarFlatAssembler< FEC, DV > , FEC, DV, double >::scalar(const FERequirement &feRequirements, ScalarAffordance affordance)
Calculates the scalar quantity requested by feRequirements and affordance.
feRequirements Reference to the finite element requirements. affordance The scalar affordance Const reference to the calculated scalar quantity.
const ScalarType & Ikarus::ScalarAssembler< ScalarFlatAssembler< FEC, DV > , FEC, DV, double >::scalar()
Calculates the scalar quantity requested by the bound feRequirements and returns a reference.
Const reference to the calculated scalar quantity.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::reducedSize()
Returns the size of the free degrees of freedom, which are not fixed by a Dirichlet boundary condition.
Size of the reduced degrees of freedom.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::size()
Returns the size of nodes, i.e., the number of degrees of freedom.
Size of the degrees of freedom.
Eigen::VectorXd Ikarus::FlatAssemblerBase< B, FEC >::createFullVector(Eigen::Ref< const Eigen::VectorXd > reducedVector)
Creates the full-sized vector of size Dof and inserts the values of a reduced vector at the "free" degrees of freedom and writes a zero for the fixed doffs.
reducedVector Reference to the reduced vector. Eigen::VectorXd The full-sized vector.
auto & Ikarus::FlatAssemblerBase< FEC, DV >::finiteElements() const
Returns the container of finite elements.
Reference to the finite element container.
const auto & Ikarus::FlatAssemblerBase< FEC, DV >::dirichletValues() const
Returns the dirichlet value object.
Reference to the dirichlet value object.
const auto & Ikarus::FlatAssemblerBase< FEC, DV >::gridView() const
Returns the gridView object.
Reference to the gridView object.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::constraintsBelow(SizeType i) const
Returns the number of constraints below a given degrees of freedom index.
i Index of the degree of freedom. Number of constraints below the given index.
bool Ikarus::FlatAssemblerBase< FEC, DV >::isConstrained(SizeType i) const
Returns true if a given degree of freedom is fixed by a Dirichlet boundary condition.
i Index of the degree of freedom. True if the degree of freedom is fixed; false otherwise.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::estimateOfConnectivity() const
Coarse estimate of node connectivity, i.e., this relates to the bandwidth of a sparse matrix. This estimate overestimates the real connectivity and should only be used for allocating vectors.
Size_t Coarse estimate of node connectivity.
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(const FERequirement &req, AffordanceCollectionType affordanceCollection, DBCOption dbcOption=DBCOption::Full)
Binds the assembler to a set of finite element requirement and affordance.
req Reference to the finite element requirement. affordanceCollection The affordance collection
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(const FERequirement &req)
Binds the assembler to a finite element requirement.
req Reference to the finite element requirement.
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(AffordanceCollectionType affordanceCollection)
Binds the assembler to an affordance collection.
affordanceCollection The affordance collection
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(DBCOption dbcOption)
Binds the assembler to an affordance collection.
dbcOption The EnforcingDBC option
bool Ikarus::FlatAssemblerBase< FEC, DV >::bound() const
Returns true if the assembler is bound to a finite element requirement and affordance.
True if the assembler is bound; false otherwise.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToRequirement() const
Returns true if the assembler is bound to a finite element requirement.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToAffordanceCollection() const
Returns true if the assembler is bound to an affordance collection.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToDBCOption() const
Returns true if the assembler is bound to an affordance collection.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
FERequirement & Ikarus::FlatAssemblerBase< FEC, DV >::requirement()
Returns the requirement.
AffordanceCollectionType Ikarus::FlatAssemblerBase< FEC, DV >::affordanceCollection() const
Returns the affordance.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bind.
DBCOption Ikarus::FlatAssemblerBase< FEC, DV >::dBCOption() const
Returns the dirichlet boundary condition enforcement option.