Ikarus::EnhancedAssumedStrains
using Ikarus::EnhancedAssumedStrains< DFE >::DisplacementBasedElement = DFE
using Ikarus::EnhancedAssumedStrains< DFE >::FERequirementType = typename DisplacementBasedElement::FERequirementType
using Ikarus::EnhancedAssumedStrains< DFE >::LocalView = typename DisplacementBasedElement::LocalView
using Ikarus::EnhancedAssumedStrains< DFE >::Geometry = typename DisplacementBasedElement::Geometry
using Ikarus::EnhancedAssumedStrains< DFE >::GridView = typename DisplacementBasedElement::GridView
using Ikarus::EnhancedAssumedStrains< DFE >::Traits = typename DisplacementBasedElement::Traits
EAS::EASVariant<Geometry> Ikarus::EnhancedAssumedStrains< DFE >::easVariant_
Eigen::MatrixXd Ikarus::EnhancedAssumedStrains< DFE >::L_
Ikarus::EnhancedAssumedStrains< DFE >::EnhancedAssumedStrains(Args &&... args)
Constructor for Enhanced Assumed Strains elements.
Disabling this forwarding constructor if the argument provided is EnhancedAssumedStrains itself, to forward the calls to the implicit copy constructor Args Variadic template for constructor arguments. args Constructor arguments forwarded to the base class.
double Ikarus::EnhancedAssumedStrains< DFE >::calculateScalar(const FERequirementType &par) const
Calculates a scalar quantity for the element.
This function calculates a scalar quantity for the element based on the FERequirementType. par The FERequirementType object. Computed scalar quantity.
bool Ikarus::EnhancedAssumedStrains< DFE >::isDisplacementBased() const
Checks if the element is displacement-based and the EAS is turned off.
True if the element is displacement-based, false otherwise.
Referenced by Ikarus::EnhancedAssumedStrains< DFE >::calculateScalar, Ikarus::EnhancedAssumedStrains< DFE >::calculateScalarImpl, Ikarus::EnhancedAssumedStrains< DFE >::setEASType.
void Ikarus::EnhancedAssumedStrains< DFE >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculates vectorial quantities for the element.
This function calculates the vectorial quantities for the element based on the FERequirementType. par The FERequirementType object. force Vector to store the calculated forces.
const auto & Ikarus::EnhancedAssumedStrains< DFE >::easVariant() const
Gets the variant representing the type of Enhanced Assumed Strains (EAS).
Const reference to the EAS variant.
auto Ikarus::EnhancedAssumedStrains< DFE >::numberOfEASParameters() const
Gets the number of EAS parameters based on the current EAS type.
Number of EAS parameters.
Referenced by Ikarus::EnhancedAssumedStrains< DFE >::setEASType.
void Ikarus::EnhancedAssumedStrains< DFE >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculates the matrix for the element.
This function calculates the matrix for the element based on the FERequirementType. par The FERequirementType object. K Matrix to store the calculated stiffness.
auto Ikarus::EnhancedAssumedStrains< DFE >::calculateAt(const FERequirementType &req, const Dune::FieldVector< double, Traits::mydim > &local) const
Calculates a requested result at a specific local position using the Enhanced Assumed Strains (EAS) method.
This function calculates the results at the specified local coordinates . It takes into account the displacement-based element calculations and, if applicable, incorporates the EAS method for enhanced accuracy. req The result requirements. local The local coordinates at which results are to be calculated. calculated result resType The type representing the requested result.
void Ikarus::EnhancedAssumedStrains< DFE >::setEASType(int numberOfEASParameters)
Sets the EAS type for 2D elements.
numberOfEASParameters The number of EAS parameters
ScalarType Ikarus::EnhancedAssumedStrains< DFE >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::EnhancedAssumedStrains< DFE >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::EnhancedAssumedStrains< DFE >::calculateDAndLMatrix(const auto &easFunction, const auto &par, Eigen::Matrix< double, enhancedStrainSize, enhancedStrainSize > &DMat, Eigen::MatrixXd &LMat) const