Ikarus::SparseFlatAssembler
using Ikarus::SparseFlatAssembler< FEC, DV >::FEContainerRaw = std::remove_cvref_t<FEC>
Type of the raw finite element container.
using Ikarus::SparseFlatAssembler< FEC, DV >::Base = VectorFlatAssembler<FEC, DV>
using Ikarus::SparseFlatAssembler< FEC, DV >::GridView = typename Basis::GridView
Type of the grid view.
using Ikarus::FlatAssemblerBase< FEC, DV >::Basis = typename DV::Basis
Type of the basis.
using Ikarus::FlatAssemblerBase< FEC, DV >::DirichletValuesType = DV
Type of the Dirichlet values.
using Ikarus::FlatAssemblerBase< FEC, DV >::FEContainer = FEC
Type of the finite element container.
using Ikarus::FlatAssemblerBase< FEC, DV >::FERequirement = typename FEContainerRaw::value_type::Requirement
Type of the finite element requirement.
using Ikarus::FlatAssemblerBase< FEC, DV >::GlobalIndex = typename FEContainerRaw::value_type::GlobalIndex
Type of the global index.
using Ikarus::FlatAssemblerBase< FEC, DV >::FEContainerType = std::conditional_t<std::is_reference_v<FEContainer>, const FEContainer, FEContainer>
Type of the finite element container (reference or by value).
using Ikarus::FlatAssemblerBase< FEC, DV >::AffordanceCollectionType = AffordanceCollection<ScalarAffordance, VectorAffordance, MatrixAffordance>
Eigen::SparseMatrix<double> Ikarus::SparseFlatAssembler< FEC, DV >::spMatRaw_
Raw sparse matrix without changes for dirichlet degrees of freedom.
Eigen::SparseMatrix<double> Ikarus::SparseFlatAssembler< FEC, DV >::spMat_
Sparse matrix.
Eigen::SparseMatrix<double> Ikarus::SparseFlatAssembler< FEC, DV >::spMatReduced_
Reduced sparse matrix.
std::vector<std::vector<Eigen::Index> > Ikarus::SparseFlatAssembler< FEC, DV >::elementLinearIndices_
Vector storing indices of matrix entries in linear storage.
std::vector<std::vector<Eigen::Index> > Ikarus::SparseFlatAssembler< FEC, DV >::elementLinearReducedIndices_
Vector storing indices of matrix entries in linear storage.
bool Ikarus::SparseFlatAssembler< FEC, DV >::sparsePreProcessorRaw_
bool Ikarus::SparseFlatAssembler< FEC, DV >::sparsePreProcessor_
bool Ikarus::SparseFlatAssembler< FEC, DV >::sparsePreProcessorReduced_
flags that store if the sparsity pattern construction happened
Ikarus::SparseFlatAssembler< FEC, DV >::SparseFlatAssembler(FEContainer &&fes, const DirichletValuesType &dirichletValues)
Constructor for SparseFlatAssembler.
fes Finite element container. dirichletValues Reference to Dirichlet values.
const Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< FEC, DV >::matrix(const FERequirement &feRequirements, MatrixAffordance affordance, DBCOption dbcOption=DBCOption::Full)
Calculates the matrix quantity requested by feRequirements and the affordance. For DBCOption::Full a zero is written on fixed degrees of freedom rows and columns, and a one is written on the diagonal. For DBCOption::Raw the untouched matrix is returned. For DBCOption::Reduced the matrix is reduced in size by removing the fixed degrees of freedom.
feRequirements Reference to the finite element requirements. affordance The matrix affordance dbcOption The DBCOption Const reference to the modified sparse matrix quantity.
const Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< FEC, DV >::matrix(DBCOption dbcOption)
Calculates the matrix quantity requested by the bound feRequirements and the affordance.
const Eigen::SparseMatrix<double>& matrix(const FERequirement& feRequirements,MatrixAffordance affordance, DBCOption dbcOption) dbcOption The DBCOption Const reference to the modified sparse matrix quantity.
const Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< FEC, DV >::matrix()
Calculates the matrix quantity requested by the bound feRequirements, the affordance and the dBCOption.
const Eigen::SparseMatrix<double>& matrix(const FERequirement& feRequirements,MatrixAffordance affordance, DBCOption dbcOption) Const reference to the modified sparse matrix quantity.
Referenced by Ikarus::SparseFlatAssembler< FEC, DV >::matrix.
const Eigen::VectorXd & Ikarus::VectorFlatAssembler< FEC, DV >::vector(const FERequirement &feRequirements, VectorAffordance affordance, DBCOption dbcOption=DBCOption::Full)
Calculates the vectorial quantity requested by the feRequirements and the affordance. Depending on the requested DBCOption, the raw, reduced or full vector is returned. Raw means the degrees of freedom associated with dirichlet boundary conditions are not changed. Full means that degrees of freedom associated with dirichlet boundary conditions are set to zero in the vector. Reduced means that degrees of freedom associated with dirichlet boundary conditions are removed and the returned vector has reduced size.
feRequirements Reference to the finite element requirements. affordance The vector affordance dbcOption The DBCOption Const reference to the calculated vectorial quantity.
const Eigen::VectorXd & Ikarus::VectorFlatAssembler< FEC, DV >::vector(DBCOption dbcOption)
Calculates the vectorial quantity requested by the bound feRequirements and the affordance. Depending on the requested DBCOption, the raw, reduced or full vector is returned. Raw means the degrees of freedom associated with dirichlet boundary conditions are not changed. Full means that degrees of freedom associated with dirichlet boundary conditions are set to zero in the vector. Reduced means that degrees of freedom associated with dirichlet boundary conditions are removed and the returned vector has reduced size.
dbcOption The DBCOption Const reference to the calculated vectorial quantity.
const Eigen::VectorXd & Ikarus::VectorFlatAssembler< FEC, DV >::vector()
Calculates the vectorial quantity requested by the bound feRequirements, the affordance and the dBCOption. Depending on the DBCOption, the raw, reduced or full vector is returned. Raw means the degrees of freedom associated with dirichlet boundary conditions are not changed. Full means that degrees of freedom associated with dirichlet boundary conditions are set to zero in the vector. Reduced means that degrees of freedom associated with dirichlet boundary conditions are removed and the returned vector has reduced size.
Const reference to the calculated vectorial quantity.
Referenced by Ikarus::VectorFlatAssembler< FEC, DV >::vector.
const double & Ikarus::ScalarAssembler< FEC, DV >::scalar(const FERequirement &feRequirements, ScalarAffordance affordance)
Calculates the scalar quantity requested by feRequirements and affordance.
feRequirements Reference to the finite element requirements. affordance The scalar affordance Const reference to the calculated scalar quantity.
const double & Ikarus::ScalarAssembler< FEC, DV >::scalar()
Calculates the scalar quantity requested by the bound feRequirements and returns a reference.
Const reference to the calculated scalar quantity.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::reducedSize()
Returns the size of the free degrees of freedom, which are not fixed by a Dirichlet boundary condition.
Size of the reduced degrees of freedom.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::size()
Returns the size of nodes, i.e., the number of degrees of freedom.
Size of the degrees of freedom.
Eigen::VectorXd Ikarus::FlatAssemblerBase< B, FEC >::createFullVector(Eigen::Ref< const Eigen::VectorXd > reducedVector)
Creates the full-sized vector of size Dof and inserts the values of a reduced vector at the "free" degrees of freedom and writes a zero for the fixed doffs.
reducedVector Reference to the reduced vector. Eigen::VectorXd The full-sized vector.
auto & Ikarus::FlatAssemblerBase< FEC, DV >::finiteElements() const
Returns the container of finite elements.
Reference to the finite element container.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::constraintsBelow(size_t i) const
Returns the number of constraints below a given degrees of freedom index.
i Index of the degree of freedom. Number of constraints below the given index.
bool Ikarus::FlatAssemblerBase< FEC, DV >::isConstrained(size_t i) const
Returns true if a given degree of freedom is fixed by a Dirichlet boundary condition.
i Index of the degree of freedom. True if the degree of freedom is fixed; false otherwise.
size_t Ikarus::FlatAssemblerBase< FEC, DV >::estimateOfConnectivity() const
Coarse estimate of node connectivity, i.e., this relates to the bandwidth of a sparse matrix. This estimate overestimates the real connectivity and should only be used for allocating vectors.
Size_t Coarse estimate of node connectivity.
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(const FERequirement &req, AffordanceCollectionType affordanceCollection, DBCOption dbcOption=DBCOption::Full)
Binds the assembler to a set of finite element requirement and affordance.
req Reference to the finite element requirement. affordanceCollection The affordance collection
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(const FERequirement &req)
Binds the assembler to a finite element requirement.
req Reference to the finite element requirement.
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(AffordanceCollectionType affordanceCollection)
Binds the assembler to an affordance collection.
affordanceCollection The affordance collection
void Ikarus::FlatAssemblerBase< FEC, DV >::bind(DBCOption dbcOption)
Binds the assembler to an affordance collection.
dbcOption The EnforcingDBC option
bool Ikarus::FlatAssemblerBase< FEC, DV >::bound() const
Returns true if the assembler is bound to a finite element requirement and affordance.
True if the assembler is bound; false otherwise.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToRequirement() const
Returns true if the assembler is bound to a finite element requirement.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToAffordanceCollection() const
Returns true if the assembler is bound to an affordance collection.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
bool Ikarus::FlatAssemblerBase< FEC, DV >::boundToDBCOption() const
Returns true if the assembler is bound to an affordance collection.
True if the assembler is bound; false otherwise.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bound.
FERequirement & Ikarus::FlatAssemblerBase< FEC, DV >::requirement()
Returns the requirement.
Referenced by Ikarus::SparseFlatAssembler< FEC, DV >::matrix, Ikarus::DenseFlatAssembler< FEC, DV >::matrix, Ikarus::ScalarAssembler< FEC, DV >::scalar, Ikarus::VectorFlatAssembler< FEC, DV >::vector.
AffordanceCollectionType Ikarus::FlatAssemblerBase< FEC, DV >::affordanceCollection() const
Returns the affordance.
Referenced by Ikarus::FlatAssemblerBase< FEC, DV >::bind, Ikarus::SparseFlatAssembler< FEC, DV >::matrix, Ikarus::DenseFlatAssembler< FEC, DV >::matrix, Ikarus::ScalarAssembler< FEC, DV >::scalar, Ikarus::VectorFlatAssembler< FEC, DV >::vector.
DBCOption Ikarus::FlatAssemblerBase< FEC, DV >::dBCOption() const
Returns the dirichlet boundary condition enforcement option.
Referenced by Ikarus::SparseFlatAssembler< FEC, DV >::matrix, Ikarus::DenseFlatAssembler< FEC, DV >::matrix, Ikarus::VectorFlatAssembler< FEC, DV >::vector.
void Ikarus::SparseFlatAssembler< B, FEC >::assembleRawMatrixImpl(const FERequirement &feRequirements, MatrixAffordance affordance, Eigen::SparseMatrix< double > &assemblyMat)
Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< B, FEC >::getRawMatrixImpl(const FERequirement &feRequirements, MatrixAffordance affordance)
Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< B, FEC >::getMatrixImpl(const FERequirement &feRequirements, MatrixAffordance affordance)
Eigen::SparseMatrix< double > & Ikarus::SparseFlatAssembler< B, FEC >::getReducedMatrixImpl(const FERequirement &feRequirements, MatrixAffordance affordance)
void Ikarus::SparseFlatAssembler< B, FEC >::createOccupationPattern(Eigen::SparseMatrix< double > &assemblyMat)
Calculates the non-zero entries in the full sparse matrix and passes them to the underlying Eigen sparse matrix.
void Ikarus::SparseFlatAssembler< B, FEC >::createReducedOccupationPattern(Eigen::SparseMatrix< double > &assemblyMat)
Calculates the non-zero entries in the sparse matrix and passes them to the underlying Eigen sparse matrix. The size of the matrix has the size of the free degrees of freedom.
void Ikarus::SparseFlatAssembler< B, FEC >::createLinearDOFsPerElement(Eigen::SparseMatrix< double > &assemblyMat)
Saves the degree of freedom indices of each element in the vector elementLinearIndices.
void Ikarus::SparseFlatAssembler< B, FEC >::createLinearDOFsPerElementReduced(Eigen::SparseMatrix< double > &assemblyMat)
Saves the degree of freedom indices of each element in the vector elementLinearIndices but excludes fixed degrees of freedom.
void Ikarus::SparseFlatAssembler< B, FEC >::preProcessSparseMatrix(Eigen::SparseMatrix< double > &assemblyMat)
Pre-processes the raw sparse matrix before assembly.
void Ikarus::SparseFlatAssembler< B, FEC >::preProcessSparseMatrixReduced(Eigen::SparseMatrix< double > &assemblyMat)
Pre-processes the reduced sparse matrix before assembly.