Ikarus::PowerBasisFE
using Ikarus::PowerBasisFE< B >::Traits = FETraits<B>
Type of the traits.
using Ikarus::PowerBasisFE< B >::FlatBasis = typename Traits::FlatBasis
Type of the flat basis.
using Ikarus::PowerBasisFE< B >::LocalView = typename Traits::LocalView
Type of the local view.
using Ikarus::PowerBasisFE< B >::GlobalIndex = typename Traits::GlobalIndex
Type of the global index.
using Ikarus::PowerBasisFE< B >::GridElement = typename Traits::Element
Type of the grid element.
constexpr int Ikarus::PowerBasisFE< B >::num_children
Number of children in the powerBasis.
Referenced by Ikarus::PowerBasisFE< B >::globalFlatIndices.
LocalView Ikarus::PowerBasisFE< B >::localView_
Ikarus::PowerBasisFE< B >::PowerBasisFE(const B &p_basis, const typename LocalView::Element &element)
Constructor for the PowerBasisFE class.
p_basis The power basis. element The local element.
constexpr size_t Ikarus::PowerBasisFE< B >::size() const
Get the size of the local view.
The size of the local view.
void Ikarus::PowerBasisFE< B >::globalFlatIndices(std::vector< GlobalIndex > &globalIndices) const
Get the global flat indices for the power basis.
The global indices are collected in a FlatInterLeaved order. I.e. x_0, y_0, z_0, ..., x_n, y_n, z_n globalIndices Output vector to store global indices.
const GridElement & Ikarus::PowerBasisFE< B >::gridElement() const
Get the grid element associated with the local view.
The grid element.
Referenced by Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateAt, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateMatrix, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< B, FER, useEigenRef >::calculateVectorImpl, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::calculateVectorImpl.
const LocalView & Ikarus::PowerBasisFE< B >::localView() const
Get the const reference to the local view.
The const reference to the local view.
Referenced by Ikarus::LinearElastic< B, FER, useEigenRef >::displacementFunction, Ikarus::NonLinearElastic< B, MAT, FER, useEigenRef >::displacementFunction, Ikarus::KirchhoffLoveShell< B, FER, useEigenRef >::displacementFunction.
LocalView & Ikarus::PowerBasisFE< B >::localView()
Get the reference to the local view.
The reference to the local view.