Ikarus::LinearElastic
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::Base = FEBase<BH, useFlat, FER, useEigenRef>
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::Traits = typename Base::Traits
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::BasisHandler = typename Traits::BasisHandler
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::FlatBasis = typename Traits::FlatBasis
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::FERequirementType = typename Traits::FERequirementType
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::LocalView = typename Traits::LocalView
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::Geometry = typename Traits::Geometry
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::GridView = typename Traits::GridView
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::Element = typename Traits::Element
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::VolumeType = Volume<LinearElastic, Traits>
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::TractionType = Traction<LinearElastic, Traits>
using Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::GlobalIndex = typename Traits::GlobalIndex
Type of the global index.
using Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::GridElement = typename Traits::Element
Type of the grid element.
constexpr int Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::myDim
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVectorImpl, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::materialTangent.
constexpr int Ikarus::Volume< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::worldDim
constexpr int Ikarus::Traction< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::worldDim
std::shared_ptr<const Geometry> Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::localBasis_
double Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::emod_
double Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::nu_
size_t Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::numberOfNodes_
int Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::order_
Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::LinearElastic(const BasisHandler &basisHandler, const typename LocalView::Element &element, double emod, double nu, VolumeLoad volumeLoad={}, const BoundaryPatch< GridView > *neumannBoundary=nullptr, NeumannBoundaryLoad neumannBoundaryLoad={})
Constructor for the LinearElastic class.
VolumeLoad The type for the volume load function. NeumannBoundaryLoad The type for the Neumann boundary load function. basisHandler The basis handler for the finite element. element The element for which the finite element is constructed. emod Young's modulus. nu Poisson's ratio. volumeLoad Volume load function (default is LoadDefault). neumannBoundary Neumann boundary patch (default is nullptr). neumannBoundaryLoad Neumann boundary load function (default is LoadDefault).
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Gets the displacement function for the given FERequirementType and optional displacement vector.
ScalarType The scalar type for the displacement vector. par The FERequirementType object. dx Optional displacement vector. The displacement function.
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::strainFunction.
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::strainFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Gets the strain function for the given FERequirementType and optional displacement vector.
ScalarType The scalar type for the strain vector. par The FERequirementType object. dx Optional displacement vector. The strain function.
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateAt, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVectorImpl.
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::materialTangent() const
Gets the material tangent matrix for the linear elastic material.
The material tangent matrix.
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateAt, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVectorImpl, Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::materialTangentFunction.
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::materialTangentFunction(const FERequirementType &par) const
Gets the material tangent function for the given FERequirementType.
par The FERequirementType object. The material tangent function.
const Geometry & Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::geometry() const
size_t Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::numberOfNodes() const
int Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::order() const
double Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalar(const FERequirementType &par) const
Calculates the scalar energy for the given FERequirementType.
par The FERequirementType object. The scalar energy.
void Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculates the vector force for the given FERequirementType.
par The FERequirementType object. force Vector to store the calculated force.
void Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculates the matrix stiffness for the given FERequirementType.
par The FERequirementType object. K Matrix to store the calculated stiffness.
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateAt(const FERequirementType &req, const Dune::FieldVector< double, Traits::mydim > &local) const
Calculates a requested result at a specific local position.
req The FERequirementType object holding the global solution. local Local position vector. calculated result resType The type representing the requested result.
constexpr size_t Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::size() const
Get the size of the local view.
The size of the local view.
const GridElement & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::gridElement() const
Get the grid element associated with the local view.
The grid element.
const LocalView & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::localView() const
Get the const reference to the local view.
The const reference to the local view.
LocalView & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::localView()
Get the reference to the local view.
The reference to the local view.
auto Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Volume< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Volume< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
void Ikarus::Volume< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
auto Ikarus::Traction< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Traction< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > dx=std::nullopt) const
void Ikarus::Traction< LinearElastic< BH, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const