Ikarus::KirchhoffLoveShell
using Ikarus::KirchhoffLoveShell< PreFE, FE >::Traits = PreFE::Traits
using Ikarus::KirchhoffLoveShell< PreFE, FE >::BasisHandler = typename Traits::BasisHandler
using Ikarus::KirchhoffLoveShell< PreFE, FE >::FlatBasis = typename Traits::FlatBasis
using Ikarus::KirchhoffLoveShell< PreFE, FE >::Requirement = FERequirementsFactory<FESolutions::displacement, FEParameter::loadfactor, Traits::useEigenRef>::type
using Ikarus::KirchhoffLoveShell< PreFE, FE >::LocalView = typename Traits::LocalView
using Ikarus::KirchhoffLoveShell< PreFE, FE >::Geometry = typename Traits::Geometry
using Ikarus::KirchhoffLoveShell< PreFE, FE >::GridView = typename Traits::GridView
using Ikarus::KirchhoffLoveShell< PreFE, FE >::Element = typename Traits::Element
using Ikarus::KirchhoffLoveShell< PreFE, FE >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::KirchhoffLoveShell< PreFE, FE >::Pre = KirchhoffLoveShellPre
using Ikarus::KirchhoffLoveShell< PreFE, FE >::SupportedResultTypes = std::tuple<>
constexpr int Ikarus::KirchhoffLoveShell< PreFE, FE >::myDim
constexpr int Ikarus::KirchhoffLoveShell< PreFE, FE >::worldDim
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl.
constexpr int Ikarus::KirchhoffLoveShell< PreFE, FE >::membraneStrainSize
constexpr int Ikarus::KirchhoffLoveShell< PreFE, FE >::bendingStrainSize
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::KirchhoffLoveShell< PreFE, FE >::localBasis_
YoungsModulusAndPoissonsRatio Ikarus::KirchhoffLoveShell< PreFE, FE >::mat_
double Ikarus::KirchhoffLoveShell< PreFE, FE >::thickness_
size_t Ikarus::KirchhoffLoveShell< PreFE, FE >::numberOfNodes_
int Ikarus::KirchhoffLoveShell< PreFE, FE >::order_
Ikarus::KirchhoffLoveShell< PreFE, FE >::KirchhoffLoveShell(const Pre &pre)
Constructor for the KirchhoffLoveShell class.
Initializes the KirchhoffLoveShell instance with the given parameters. pre The pre fe
auto Ikarus::KirchhoffLoveShell< PreFE, FE >::displacementFunction(const Requirement &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const
Get the displacement function and nodal displacements.
Retrieves the displacement function and nodal displacements based on the given FERequirements. ST The scalar type used for calculations. par The FERequirements. dx Optional additional displacement vector. The displacement function.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateVectorImpl.
Geometry Ikarus::KirchhoffLoveShell< PreFE, FE >::geometry() const
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::displacementFunction.
size_t Ikarus::KirchhoffLoveShell< PreFE, FE >::numberOfNodes() const
int Ikarus::KirchhoffLoveShell< PreFE, FE >::order() const
auto Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateAtImpl(const Requirement &req, const Dune::FieldVector< double, Traits::mydim > &local) -> ResultWrapper< RT< double, myDim, worldDim >, ResultShape::Vector >
Calculates a requested result at a specific local position.
req The FERequirementType object holding the global solution. local Local position vector. calculated result RT The type representing the requested result.
void Ikarus::KirchhoffLoveShell< PreFE, FE >::bindImpl()
A helper function to bind the local view to the element.
auto Ikarus::KirchhoffLoveShell< PreFE, FE >::computeMaterialAndStrains(const Dune::FieldVector< double, 2 > &gpPos, int gpIndex, const Geometry &geo, const auto &uFunction) const
Compute material properties and strains at a given integration point.
gpPos The position of the integration point. gpIndex The index of the integration point. geo The geometry object providing position and derivatives. uFunction The function representing the displacement field. A tuple containing the material tangent, membrane strain, bending, Jacobian matrix of the reference position, Jacobian matrix of the current position, Hessian matrix of the current position, Hessian matrix of the reference position, normal vector, and normalized normal vector at the given integration point.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateVectorImpl.
void Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl(const Requirement &par, const MatrixAffordance &affordance, typename Traits::template MatrixType< ST > K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const
void Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateVectorImpl(const Requirement &par, const VectorAffordance &affordance, typename Traits::template VectorType< ST > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const
auto Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateScalarImpl(const Requirement &par, const ScalarAffordance &affordance, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const -> ST
Eigen::Matrix< ST, 3, 3 > Ikarus::KirchhoffLoveShell< PreFE, FE >::kgBending(const Eigen::Matrix< ST, 2, 3 > &jcur, const Eigen::Matrix3< ST > &h, const auto &dN, const auto &ddN, const Eigen::Vector3< ST > &a3N, const Eigen::Vector3< ST > &a3, const Eigen::Vector3< ST > &S, int I, int J) const
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl.
Eigen::Matrix< ST, 3, 3 > Ikarus::KirchhoffLoveShell< PreFE, FE >::bopBending(const Eigen::Matrix< ST, 2, 3 > &jcur, const Eigen::Matrix3< ST > &h, const auto &dN, const auto &ddN, const int node, const Eigen::Vector3< ST > &a3N, const Eigen::Vector3< ST > &a3) const
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateVectorImpl.
Eigen::Matrix< double, 3, 3 > Ikarus::KirchhoffLoveShell< PreFE, FE >::materialTangent(const Eigen::Matrix< double, 3, 3 > &Aconv) const
Gets the material tangent matrix for the linear elastic material.
Aconv A tensor to get the material tangent in the curvilinear coordinate system. The material tangent matrix.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::computeMaterialAndStrains.
static consteval bool Ikarus::KirchhoffLoveShell< PreFE, FE >::canProvideResultType()
Returns whether an element can provide a requested result. Can be used in constant expressions.
RT The type representing the requested result. boolean indicating if a requested result can be provided
const auto & Ikarus::KirchhoffLoveShell< PreFE, FE >::underlying() const
auto & Ikarus::KirchhoffLoveShell< PreFE, FE >::underlying()