Ikarus::NonLinearElastic
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::Traits = TraitsFromFE<Basis_, FERequirements_, useEigenRef>
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::Basis = typename Traits::Basis
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::FlatBasis = typename Traits::FlatBasis
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::FERequirementType = typename Traits::FERequirementType
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::LocalView = typename Traits::LocalView
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::Geometry = typename Traits::Geometry
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::GridView = typename Traits::GridView
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::Element = typename Traits::Element
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::ResultRequirementsType = typename Traits::ResultRequirementsType
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::BasePowerFE = PowerBasisFE<FlatBasis>
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::Material = Material_
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::VolumeType = Volume<NonLinearElastic<Basis_, Material_, FERequirements_, useEigenRef>, Traits>
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::TractionType = Traction<NonLinearElastic<Basis_, Material_, FERequirements_, useEigenRef>, Traits>
using Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::RootBasis = Basis_::FlatBasis
Type of the root basis.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GlobalIndex = typename LocalView::MultiIndex
Type of the global index.
using Ikarus::PowerBasisFE< Basis_::FlatBasis >::GridElement = typename LocalView::Element
Type of the grid element.
constexpr int Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::myDim
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl.
constexpr auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::strainType
constexpr int Ikarus::PowerBasisFE< Basis_::FlatBasis >::num_children
Number of children in the powerBasis.
constexpr int Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::worldDim
constexpr int Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::worldDim
std::shared_ptr<const Geometry> Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::localBasis
Material Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::mat
size_t Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::numberOfNodes_
int Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::order_
Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::NonLinearElastic(const Basis &globalBasis, const typename LocalView::Element &element, const Material &p_mat, VolumeLoad p_volumeLoad={}, const BoundaryPatch< GridView > *p_neumannBoundary=nullptr, NeumannBoundaryLoad p_neumannBoundaryLoad={})
Constructor for the NonLinearElastic class.
VolumeLoad The type for the volume load function. NeumannBoundaryLoad The type for the Neumann boundary load function. globalBasis The global basis for the finite element. element The element for which the finite element is constructed. p_mat The material for the non-linear elastic element. p_volumeLoad Volume load function (default is LoadDefault). p_neumannBoundary Neumann boundary patch (default is nullptr). p_neumannBoundaryLoad Neumann boundary load function (default is LoadDefault).
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Get the displacement function for the given FERequirementType.
ScalarType The scalar type for the displacement function. par The FERequirementType object. dx Optional displacement vector. A StandardLocalFunction representing the displacement function.
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateAt, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::strainFunction.
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::strainFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
The strain function for the given FERequirementType.
ScalarType The scalar type for the strain function. par The FERequirementType object. dx Optional displacement vector. The strain function calculated using greenLagrangeStrains.
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl.
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::materialTangent(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the material tangent for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt Flag indicating whether to use Voigt notation. strain The strain vector. The material tangent calculated using the material's tangentModuli function.
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix.
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::getInternalEnergy(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the internal energy for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. strain The strain vector. The internal energy calculated using the material's storedEnergy function.
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl.
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::getStress(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the stress for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt A boolean indicating whether to use the Voigt notation for stress. strain The strain vector. The stress vector calculated using the material's stresses function.
Referenced by Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl.
const Geometry & Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::geometry() const
size_t Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::numberOfNodes() const
int Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::order() const
double Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalar(const FERequirementType &par) const
Calculate the scalar value associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. The calculated scalar value.
void Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
void Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateAt(const ResultRequirementsType &req, const Dune::FieldVector< double, Traits::mydim > &local, ResultTypeMap< double > &result) const
Calculate specified results at a given local position.
req The ResultRequirementsType object specifying the required results. local The local position for which results are to be calculated. result The ResultTypeMap object to store the calculated results.
constexpr size_t Ikarus::PowerBasisFE< Basis_::FlatBasis >::size() const
Get the size of the local view.
The size of the local view.
void Ikarus::PowerBasisFE< Basis_::FlatBasis >::globalFlatIndices(std::vector< GlobalIndex > &globalIndices) const
Get the global flat indices for the power basis.
The global indices are collected in a FlatInterLeaved order. I.e. x_0, y_0, z_0, ..., x_n, y_n, z_n globalIndices Output vector to store global indices.
const GridElement & Ikarus::PowerBasisFE< Basis_::FlatBasis >::gridElement() const
Get the grid element associated with the local view.
The grid element.
const LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView() const
Get the const reference to the local view.
The const reference to the local view.
LocalView & Ikarus::PowerBasisFE< Basis_::FlatBasis >::localView()
Get the reference to the local view.
The reference to the local view.
double Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
double Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
void Ikarus::Volume< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > dx=std::nullopt) const
void Ikarus::Traction< NonLinearElastic< Basis_, Material_, FERequirements<>, false > , TraitsFromFE< Basis_, FERequirements<>, false > >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const