Ikarus::FE
using Ikarus::FE< PreFE, Skills >::Mixin = FEMixin<PreFE, Skills...>
Type of the FE mixin.
using Ikarus::FE< PreFE, Skills >::Traits = PreFE::Traits
Type traits.
using Ikarus::FE< PreFE, Skills >::BasisHandler = Traits::BasisHandler
Type of the basisHandler.
using Ikarus::FE< PreFE, Skills >::LocalView = typename Traits::LocalView
Type of the local view.
using Ikarus::FE< PreFE, Skills >::GridView = typename Traits::GridView
Type of the global view.
using Ikarus::FE< PreFE, Skills >::GlobalIndex = typename Traits::GlobalIndex
Type of the global index.
using Ikarus::FE< PreFE, Skills >::GridElement = typename Traits::Element
Type of the grid element.
using Ikarus::FE< PreFE, Skills >::PreTuple = std::tuple<typename Skills<PreFE, FE>::Pre...>
using Ikarus::FEMixin< PreFE, Skills... >::SupportedResultTypes = decltype(std::tuple_cat(computeSupportedResultTypes<Skills... <PreFE, typename PreFE::template FE<Skills... ...> >>()...))
Type alias for the supported result types by the mixin.
using Ikarus::FEMixin< PreFE, Skills... >::Requirement = RequirementType<requirementDetected>::type
friend Ikarus::FE< PreFE, Skills >::Mixin
constexpr int Ikarus::FE< PreFE, Skills >::myDim
constexpr int Ikarus::FE< PreFE, Skills >::worldDim
Ikarus::FE< PreFE, Skills >::FE(const BasisHandler &basisHandler, typename Skills< PreFE, FE >::Pre... skillsArgs)
Constructor for the FE class.
basisHandler The basis handler. skillsArgs Skill arguments.
void Ikarus::FE< PreFE, Skills >::bind(const GridElement &element)
Convenient function to bind the local view to the element.
element The element to be bounded
Referenced by Ikarus::Python::registerFE.
constexpr size_t Ikarus::FE< PreFE, Skills >::size() const
Get the size of the local view.
The size of the local view.
const GridElement & Ikarus::FE< PreFE, Skills >::gridElement() const
Get the grid element associated with the local view.
The grid element.
Referenced by Ikarus::utils::referenceElementSubEntityPositions.
const LocalView & Ikarus::FE< PreFE, Skills >::localView() const
Get the const reference to the local view.
The const reference to the local view.
Referenced by Ikarus::Python::registerFE.
LocalView & Ikarus::FE< PreFE, Skills >::localView()
Get the reference to the local view.
The reference to the local view.
auto Ikarus::FEMixin< PreFE, Skills... >::calculateAt(const Requirement &req, const Dune::FieldVector< double, Traits::mydim > &local) const
Calculate the element values at a specific location for a given ResultType.
RT The ResultType to calculate. req The Requirement object specifying the requirements for the calculation. local The local coordinates where the calculation is performed. The calculated result as specified by the ResultType.
void Ikarus::FEMixin< PreFE, Skills... >::bind()
Call all bind functions if the skill implements it.
auto Ikarus::FEMixin< PreFE, Skills... >::calculateScalarImpl(const Requirement &par, ScalarAffordance affordance, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Calculate the scalar value in each skill and joins them by +.
ScalarType The scalar type for the calculation. par The Requirement object specifying the requirements for the calculation. dx Optional vector used in the calculation. The calculated scalar value.
void Ikarus::FEMixin< PreFE, Skills... >::calculateVectorImpl(const Requirement &par, VectorAffordance affordance, typename Traits::template VectorType< ScalarType > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Calculate the vector for each skill.
ScalarType The scalar type for the calculation. par The Requirement object specifying the requirements for the calculation. force The vector to store the calculated result. dx Optional vector used in the calculation.
void Ikarus::FEMixin< PreFE, Skills... >::calculateMatrixImpl(const Requirement &par, MatrixAffordance affordance, typename Traits::template MatrixType< ScalarType > K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Calculate the matrix for each skill.
ScalarType The scalar type for the calculation. par The Requirement object specifying the requirements for the calculation. K The matrix to store the calculated result. dx Optional vector used in the calculation.
static consteval bool Ikarus::FEMixin< PreFE, Skills... >::hasSkill()
Checks if the mixin class has a specific skill.
Skill The skill to check for. True if the skill is present, false otherwise.
static auto Ikarus::FEMixin< PreFE, Skills... >::createRequirement()
Create a Requirement object.
The created Requirement object.
const auto & Ikarus::FEMixin< PreFE, Skills... >::underlying() const
Get a reference to the underlying finite element object.
A reference to the underlying finite element object.
auto & Ikarus::FEMixin< PreFE, Skills... >::underlying()
Get a reference to the underlying finite element object.
A reference to the underlying finite element object.