Ikarus::Experimental::AutoDiffMAT
using Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::ScalarType = typename RealMAT::ScalarType
using Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::StrainMatrix = typename RealMAT::StrainMatrix
using Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::StressMatrix = typename RealMAT::StressMatrix
using Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::MaterialTensor = typename RealMAT::MaterialTensor
using Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::MaterialParameters = typename RealMAT::MaterialParameters
constexpr int Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::dim
constexpr int Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::nVoigtIndices
Referenced by Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::tangentModuli.
constexpr auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::strainTag
constexpr auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stressTag
constexpr auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::tangentModuliTag
constexpr bool Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::energyAcceptsVoigt
constexpr bool Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stressToVoigt
constexpr bool Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stressAcceptsVoigt
constexpr bool Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::moduliToVoigt
constexpr bool Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::moduliAcceptsVoigt
constexpr double Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::derivativeFactorImpl
Referenced by Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stresses, Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::tangentModuli.
MaterialParameters Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::materialParameter_
Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::AutoDiffMAT(Args &&... args)
Constructor for the AutoDiffMAT class. Forward the construction to the underlying element.
Args Variadic template for constructor arguments. args Constructor arguments.
MaterialParameters Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::materialParametersImpl() const
Returns the material parameters stored in the material.
auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::storedEnergy(const Eigen::MatrixBase< Derived > &E) const
Computes the stored energy in the underlying material model.
Derived The derived type of the input matrix. E The strain mesasure. The stored energy.
auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stresses(const Eigen::MatrixBase< Derived > &E) const
Computes the stresses in the underlying material model.
voigt A boolean indicating whether to return stresses in Voigt notation. Derived The derived type of the input matrix. E The strain mesasure. The stresses.
auto Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::tangentModuli(const Eigen::MatrixBase< Derived > &E) const
Computes the tangent moduli in the underlying material model.
voigt A boolean indicating whether to return tangent moduli in Voigt notation. Derived The derived type of the input matrix. E The strain mesasure. The tangent moduli.
const RealMAT & Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::realMAT() const
Get the reference to the base material.
The reference to the base material.
Referenced by Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::materialParametersImpl, Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::storedEnergy, Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::stresses, Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::tangentModuli.
static constexpr std::string Ikarus::Experimental::AutoDiffMAT< RealMAT, forceAutoDiffV, forceAutoDiffS >::nameImpl() noexcept