Ikarus::Traction
using Ikarus::Traction< DisplacementBasedElement, Traits >::FERequirementType = typename Traits::FERequirementType
using Ikarus::Traction< DisplacementBasedElement, Traits >::LocalView = typename Traits::LocalView
using Ikarus::Traction< DisplacementBasedElement, Traits >::GridView = typename Traits::GridView
constexpr int Ikarus::Traction< DisplacementBasedElement, Traits >::myDim
constexpr int Ikarus::Traction< DisplacementBasedElement, Traits >::worldDim
Referenced by Ikarus::Traction< DisplacementBasedElement, Traits >::calculateVectorImpl.
std::function<Eigen::Vector<double, worldDim>(const Dune::FieldVector<double, worldDim>&, const double&)> Ikarus::Traction< DisplacementBasedElement, Traits >::neumannBoundaryLoad
const BoundaryPatch<GridView>* Ikarus::Traction< DisplacementBasedElement, Traits >::neumannBoundary
Ikarus::Traction< DisplacementBasedElement, Traits >::Traction(const BoundaryPatch< GridView > *p_neumannBoundary, NeumannBoundaryLoad p_neumannBoundaryLoad)
Constructor for the Loads class.
NeumannBoundaryLoad The type for the Neumann boundary load function. p_neumannBoundary Neumann boundary patch. p_neumannBoundaryLoad Neumann boundary load function.
double Ikarus::Traction< DisplacementBasedElement, Traits >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< DisplacementBasedElement, Traits >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< DisplacementBasedElement, Traits >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix.
auto Ikarus::Traction< DisplacementBasedElement, Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl.
void Ikarus::Traction< DisplacementBasedElement, Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > dx=std::nullopt) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl.
void Ikarus::Traction< DisplacementBasedElement, Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl.
constexpr const DisplacementBasedElement & Ikarus::Traction< DisplacementBasedElement, Traits >::dbElement() const
Const accessor to the underlying displacement-based finite element (CRTP).
Const reference to the underlying displacement-based finite element.