Ikarus::Traction
using Ikarus::Traction< DFE, Traits >::FERequirementType = typename Traits::FERequirementType
using Ikarus::Traction< DFE, Traits >::LocalView = typename Traits::LocalView
using Ikarus::Traction< DFE, Traits >::GridView = typename Traits::GridView
constexpr int Ikarus::Traction< DFE, Traits >::myDim
constexpr int Ikarus::Traction< DFE, Traits >::worldDim
Referenced by Ikarus::Traction< DFE, Traits >::calculateVectorImpl.
std::function<Eigen::Vector<double, worldDim>(const Dune::FieldVector<double, worldDim>&, const double&)> Ikarus::Traction< DFE, Traits >::neumannBoundaryLoad_
const BoundaryPatch<GridView>* Ikarus::Traction< DFE, Traits >::neumannBoundary_
Ikarus::Traction< DFE, Traits >::Traction(const BoundaryPatch< GridView > *neumannBoundary, NBL neumannBoundaryLoad)
Constructor for the Loads class.
NBL The type for the Neumann boundary load function. neumannBoundary Neumann boundary patch. neumannBoundaryLoad Neumann boundary load function.
double Ikarus::Traction< DFE, Traits >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Traction< DFE, Traits >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Traction< DFE, Traits >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix.
auto Ikarus::Traction< DFE, Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::KirchhoffLoveShell< BH, FER, useEigenRef, useFlat >::calculateScalarImpl.
void Ikarus::Traction< DFE, Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > dx=std::nullopt) const
Referenced by Ikarus::LinearElastic< BH, FER, useEigenRef, useFlat >::calculateVectorImpl, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVectorImpl, Ikarus::KirchhoffLoveShell< BH, FER, useEigenRef, useFlat >::calculateVectorImpl.
void Ikarus::Traction< DFE, Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
Referenced by Ikarus::KirchhoffLoveShell< BH, FER, useEigenRef, useFlat >::calculateMatrixImpl.
constexpr const DFE & Ikarus::Traction< DFE, Traits >::dbElement() const
Const accessor to the underlying displacement-based finite element (CRTP).
Const reference to the underlying displacement-based finite element.