Ikarus::NonLinearElastic
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::Base = FEBase<BH, useFlat, FER, useEigenRef>
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::Traits = typename Base::Traits
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::BasisHandler = typename Traits::BasisHandler
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::FlatBasis = typename Traits::FlatBasis
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::FERequirementType = typename Traits::FERequirementType
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::LocalView = typename Traits::LocalView
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::Geometry = typename Traits::Geometry
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::GridView = typename Traits::GridView
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::Element = typename Traits::Element
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::Material = MAT
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::VolumeType = Volume<NonLinearElastic, Traits>
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::TractionType = Traction<NonLinearElastic, Traits>
using Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::GlobalIndex = typename Traits::GlobalIndex
Type of the global index.
using Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::GridElement = typename Traits::Element
Type of the grid element.
constexpr int Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::myDim
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVectorImpl.
constexpr auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::strainType
constexpr int Ikarus::Volume< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::worldDim
constexpr int Ikarus::Traction< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::worldDim
std::shared_ptr<const Geometry> Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::localBasis_
Material Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::mat_
size_t Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::numberOfNodes_
int Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::order_
Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::NonLinearElastic(const BasisHandler &basisHandler, const typename LocalView::Element &element, const Material &mat, VolumeLoad volumeLoad={}, const BoundaryPatch< GridView > *neumannBoundary=nullptr, NeumannBoundaryLoad neumannBoundaryLoad={})
Constructor for the NonLinearElastic class.
VolumeLoad The type for the volume load function. NeumannBoundaryLoad The type for the Neumann boundary load function. basisHandler The basis handler for the finite element. element The element for which the finite element is constructed. mat The material for the non-linear elastic element. volumeLoad Volume load function (default is LoadDefault). neumannBoundary Neumann boundary patch (default is nullptr). neumannBoundaryLoad Neumann boundary load function (default is LoadDefault).
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::displacementFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Get the displacement function for the given FERequirementType.
ScalarType The scalar type for the displacement function. par The FERequirementType object. dx Optional displacement vector. A StandardLocalFunction representing the displacement function.
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateAt, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::strainFunction.
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::strainFunction(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
The strain function for the given FERequirementType.
ScalarType The scalar type for the strain function. par The FERequirementType object. dx Optional displacement vector. The strain function calculated using greenLagrangeStrains.
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalarImpl, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVectorImpl.
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::materialTangent(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the material tangent for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt Flag indicating whether to use Voigt notation. strain The strain vector. The material tangent calculated using the material's tangentModuli function.
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix.
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::getInternalEnergy(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the internal energy for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. strain The strain vector. The internal energy calculated using the material's storedEnergy function.
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalarImpl.
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::getStress(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the stress for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt A boolean indicating whether to use the Voigt notation for stress. strain The strain vector. The stress vector calculated using the material's stresses function.
Referenced by Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix, Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVectorImpl.
const Geometry & Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::geometry() const
size_t Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::numberOfNodes() const
int Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::order() const
double Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalar(const FERequirementType &par) const
Calculate the scalar value associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. The calculated scalar value.
void Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVector(const FERequirementType &par, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateMatrix(const FERequirementType &par, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateAt(const FERequirementType &req, const Dune::FieldVector< double, Traits::mydim > &local) const
Calculates a requested result at a specific local position.
req The FERequirementType object holding the global solution. local Local position vector. calculated result RT The type representing the requested result.
constexpr size_t Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::size() const
Get the size of the local view.
The size of the local view.
const GridElement & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::gridElement() const
Get the grid element associated with the local view.
The grid element.
const LocalView & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::localView() const
Get the const reference to the local view.
The const reference to the local view.
LocalView & Ikarus::FEBase< BH, useFlat, FERequirements<> , useEigenRef >::localView()
Get the reference to the local view.
The reference to the local view.
static consteval bool Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::canProvideResultType()
Returns whether an element can provide a requested result. Can be used in constant expressions.
RT The type representing the requested result. boolean indicating if a requested result can be provided
auto Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
void Ikarus::NonLinearElastic< BH, MAT, FER, useEigenRef, useFlat >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
auto Ikarus::Volume< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Volume< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
void Ikarus::Volume< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const
auto Ikarus::Traction< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const -> ST
void Ikarus::Traction< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ST > force, const std::optional< const Eigen::VectorX< ST > > dx=std::nullopt) const
void Ikarus::Traction< NonLinearElastic< BH, MAT, FERequirements<>, false, true > , FEBase< BH, true, FERequirements<>, false >::Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ST > > &dx=std::nullopt) const