Ikarus::Volume
using Ikarus::Volume< DisplacementBasedElement, Traits >::FERequirementType = typename Traits::FERequirementType
using Ikarus::Volume< DisplacementBasedElement, Traits >::LocalView = typename Traits::LocalView
constexpr int Ikarus::Volume< DisplacementBasedElement, Traits >::worldDim
Referenced by Ikarus::Volume< DisplacementBasedElement, Traits >::calculateVectorImpl.
std::function<Eigen::Vector<double, worldDim>(const Dune::FieldVector<double, worldDim>&, const double&)> Ikarus::Volume< DisplacementBasedElement, Traits >::volumeLoad
Ikarus::Volume< DisplacementBasedElement, Traits >::Volume(VolumeLoad p_volumeLoad={})
Constructor for the Loads class.
VolumeLoad The type for the volume load function. p_volumeLoad Volume load function.
double Ikarus::Volume< DisplacementBasedElement, Traits >::calculateScalar(const FERequirementType &req) const
Calculate the scalar value.
Calculates the scalar value based on the given FERequirements. req The FERequirements. The calculated scalar value.
void Ikarus::Volume< DisplacementBasedElement, Traits >::calculateVector(const FERequirementType &req, typename Traits::template VectorType<> force) const
Calculate the vector associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. force The vector to store the calculated result.
void Ikarus::Volume< DisplacementBasedElement, Traits >::calculateMatrix(const FERequirementType &req, typename Traits::template MatrixType<> K) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. req The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
Referenced by Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateMatrix, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateMatrix.
auto Ikarus::Volume< DisplacementBasedElement, Traits >::calculateScalarImpl(const FERequirementType &par, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const -> ScalarType
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateScalarImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateScalarImpl.
void Ikarus::Volume< DisplacementBasedElement, Traits >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::LinearElastic< Basis_, FERequirements_, useEigenRef >::calculateVectorImpl, Ikarus::NonLinearElastic< Basis_, Material_, FERequirements_, useEigenRef >::calculateVectorImpl.
void Ikarus::Volume< DisplacementBasedElement, Traits >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< const Eigen::VectorX< ScalarType > > &dx=std::nullopt) const
Referenced by Ikarus::KirchhoffLoveShell< Basis_, FERequirements_, useEigenRef >::calculateMatrixImpl.
constexpr const DisplacementBasedElement & Ikarus::Volume< DisplacementBasedElement, Traits >::dbElement() const
Const accessor to the underlying displacement-based finite element (CRTP).
Const reference to the underlying displacement-based finite element.