Ikarus::AffordanceCollection
using Ikarus::AffordanceCollection< Affordances >::Base = std::tuple<Affordances...>
constexpr bool Ikarus::AffordanceCollection< Affordances >::hasScalarAffordance
Referenced by Ikarus::NonLinearOperatorFactory::op.
constexpr bool Ikarus::AffordanceCollection< Affordances >::hasVectorAffordance
constexpr bool Ikarus::AffordanceCollection< Affordances >::hasMatrixAffordance
Ikarus::AffordanceCollection< Affordances >::AffordanceCollection()=default
constexpr Ikarus::AffordanceCollection< Affordances >::AffordanceCollection(Affordances... affordances)
constexpr bool Ikarus::AffordanceCollection< Affordances >::hasAffordance(Affordance &&affordances) const
Check if a specific affordance is present in the requirements.
This function checks if the specified affordance is present in the requirements. Affordance Type of affordance to be checked. affordance The affordance to be checked. This can also be an affordance collection. True if the affordance is present, false otherwise.
auto Ikarus::AffordanceCollection< Affordances >::scalarAffordance() const
Referenced by Ikarus::NonLinearOperatorFactory::op.
auto Ikarus::AffordanceCollection< Affordances >::vectorAffordance() const
Referenced by Ikarus::NonLinearOperatorFactory::op.
auto Ikarus::AffordanceCollection< Affordances >::matrixAffordance() const
Referenced by Ikarus::NonLinearOperatorFactory::op.