Ikarus::LinearElastic
using Ikarus::LinearElastic< PreFE, FE, PRE >::Traits = PreFE::Traits
using Ikarus::LinearElastic< PreFE, FE, PRE >::BasisHandler = typename Traits::BasisHandler
using Ikarus::LinearElastic< PreFE, FE, PRE >::FlatBasis = typename Traits::FlatBasis
using Ikarus::LinearElastic< PreFE, FE, PRE >::Requirement = FERequirementsFactory<FESolutions::displacement, FEParameter::loadfactor, Traits::useEigenRef>::type
using Ikarus::LinearElastic< PreFE, FE, PRE >::LocalView = typename Traits::LocalView
using Ikarus::LinearElastic< PreFE, FE, PRE >::Geometry = typename Traits::Geometry
using Ikarus::LinearElastic< PreFE, FE, PRE >::GridView = typename Traits::GridView
using Ikarus::LinearElastic< PreFE, FE, PRE >::Element = typename Traits::Element
using Ikarus::LinearElastic< PreFE, FE, PRE >::Material = PRE::Material
using Ikarus::LinearElastic< PreFE, FE, PRE >::Pre = PRE
using Ikarus::LinearElastic< PreFE, FE, PRE >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::ResultTypeBase< ResultTypes >::SupportedResultTypes = std::tuple<decltype(makeRT<ResultTypes>())...>
constexpr int Ikarus::LinearElastic< PreFE, FE, PRE >::myDim
Referenced by Ikarus::LinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateVectorImpl.
std::shared_ptr<const Geometry> Ikarus::LinearElastic< PreFE, FE, PRE >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::LinearElastic< PreFE, FE, PRE >::localBasis_
Material Ikarus::LinearElastic< PreFE, FE, PRE >::mat_
size_t Ikarus::LinearElastic< PreFE, FE, PRE >::numberOfNodes_
int Ikarus::LinearElastic< PreFE, FE, PRE >::order_
Ikarus::LinearElastic< PreFE, FE, PRE >::LinearElastic(const Pre &pre)
Constructor for the LinearElastic class.
pre The pre fe
auto Ikarus::LinearElastic< PreFE, FE, PRE >::displacementFunction(const Requirement &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Gets the displacement function for the given Requirement and optional displacement vector.
ScalarType The scalar type for the displacement vector. par The Requirement object. dx Optional displacement vector. The displacement function.
Referenced by Ikarus::LinearElastic< PreFE, FE, PRE >::calculateScalarImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::strainFunction.
auto Ikarus::LinearElastic< PreFE, FE, PRE >::strainFunction(const Requirement &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Gets the strain function for the given Requirement and optional di splacement vector.
ScalarType The scalar type for the strain vector. par The Requirement object. dx Optional displacement vector. The strain function.
Referenced by Ikarus::LinearElastic< PreFE, FE, PRE >::calculateAtImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateScalarImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateVectorImpl.
auto Ikarus::LinearElastic< PreFE, FE, PRE >::materialTangent() const
Gets the material tangent matrix for the linear elastic material.
The material tangent matrix.
Referenced by Ikarus::LinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateScalarImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::calculateVectorImpl, Ikarus::LinearElastic< PreFE, FE, PRE >::materialTangentFunction.
auto Ikarus::LinearElastic< PreFE, FE, PRE >::materialTangentFunction(const Requirement &par) const
Gets the material tangent function for the given Requirement.
par The Requirement object. The material tangent function.
const Geometry & Ikarus::LinearElastic< PreFE, FE, PRE >::geometry() const
size_t Ikarus::LinearElastic< PreFE, FE, PRE >::numberOfNodes() const
int Ikarus::LinearElastic< PreFE, FE, PRE >::order() const
decltype(auto) Ikarus::LinearElastic< PreFE, FE, PRE >::material() const
auto Ikarus::LinearElastic< PreFE, FE, PRE >::calculateAtImpl(const Requirement &req, const Dune::FieldVector< double, Traits::mydim > &local, Dune::PriorityTag< 1 >) const
Calculates a requested result at a specific local position.
req The Requirement object holding the global solution. local Local position vector. RT The requested result type calculated result RT The type representing the requested result.
void Ikarus::LinearElastic< PreFE, FE, PRE >::bindImpl()
A helper function to bind the local view to the element.
void Ikarus::LinearElastic< PreFE, FE, PRE >::calculateMatrixImpl(const Requirement &par, const MatrixAffordance &affordance, typename Traits::template MatrixType<> K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
auto Ikarus::LinearElastic< PreFE, FE, PRE >::calculateScalarImpl(const Requirement &par, ScalarAffordance affordance, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const -> ScalarType
void Ikarus::LinearElastic< PreFE, FE, PRE >::calculateVectorImpl(const Requirement &par, VectorAffordance affordance, typename Traits::template VectorType< ScalarType > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
const auto & Ikarus::LinearElastic< PreFE, FE, PRE >::underlying() const
auto & Ikarus::LinearElastic< PreFE, FE, PRE >::underlying()
static consteval bool Ikarus::ResultTypeBase< ResultTypes >::supportsResultType()
Returns whether a ResultType is provided by the element.
RT requested ResultType