Ikarus::NonLinearElastic
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Traits = PreFE::Traits
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Basis = typename Traits::Basis
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::FlatBasis = typename Traits::FlatBasis
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::FERequirementType = typename Traits::FERequirementType
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::LocalView = typename Traits::LocalView
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Geometry = typename Traits::Geometry
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::GridView = typename Traits::GridView
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Element = typename Traits::Element
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Material = PRE::Material
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::Pre = PRE
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::LocalBasisType = decltype(std::declval<LocalView>().tree().child(0).finiteElement().localBasis())
using Ikarus::NonLinearElastic< PreFE, FE, PRE >::SupportedResultTypes = std::tuple<decltype(makeRT<ResultTypes::PK2Stress>())>
constexpr int Ikarus::NonLinearElastic< PreFE, FE, PRE >::myDim
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateVectorImpl.
constexpr auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::strainType
std::shared_ptr<const Geometry> Ikarus::NonLinearElastic< PreFE, FE, PRE >::geo_
Dune::CachedLocalBasis<std::remove_cvref_t<LocalBasisType> > Ikarus::NonLinearElastic< PreFE, FE, PRE >::localBasis_
Material Ikarus::NonLinearElastic< PreFE, FE, PRE >::mat_
size_t Ikarus::NonLinearElastic< PreFE, FE, PRE >::numberOfNodes_
int Ikarus::NonLinearElastic< PreFE, FE, PRE >::order_
Ikarus::NonLinearElastic< PreFE, FE, PRE >::NonLinearElastic(const Pre &pre)
Constructor for the NonLinearElastic class.
pre The pre fe
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::displacementFunction(const FERequirementType &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Get the displacement function for the given FERequirementType.
ScalarType The scalar type for the displacement function. par The FERequirementType object. dx Optional displacement vector. A StandardLocalFunction representing the displacement function.
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateAtImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::strainFunction.
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::strainFunction(const FERequirementType &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
The strain function for the given FERequirementType.
ScalarType The scalar type for the strain function. par The FERequirementType object. dx Optional displacement vector. The strain function calculated using greenLagrangeStrains.
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateScalarImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateVectorImpl.
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::materialTangent(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the material tangent for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt Flag indicating whether to use Voigt notation. strain The strain vector. The material tangent calculated using the material's tangentModuli function.
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl.
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::getInternalEnergy(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the internal energy for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. strain The strain vector. The internal energy calculated using the material's storedEnergy function.
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateScalarImpl.
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::getStress(const Eigen::Vector< ScalarType, strainDim > &strain) const
Get the stress for the given strain.
ScalarType The scalar type for the material and strain. strainDim The dimension of the strain vector. voigt A boolean indicating whether to use the Voigt notation for stress. strain The strain vector. The stress vector calculated using the material's stresses function.
Referenced by Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl, Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateVectorImpl.
const Geometry & Ikarus::NonLinearElastic< PreFE, FE, PRE >::geometry() const
size_t Ikarus::NonLinearElastic< PreFE, FE, PRE >::numberOfNodes() const
int Ikarus::NonLinearElastic< PreFE, FE, PRE >::order() const
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateAtImpl(const FERequirementType &req, const Dune::FieldVector< double, Traits::mydim > &local, Dune::PriorityTag< 1 >) const
Calculates a requested result at a specific local position.
req The FERequirementType object holding the global solution. local Local position vector. calculated result RT The type representing the requested result.
void Ikarus::NonLinearElastic< PreFE, FE, PRE >::bindImpl()
A helper function to bind the local view to the element.
void Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateMatrixImpl(const FERequirementType &par, typename Traits::template MatrixType<> K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
Calculate the matrix associated with the given FERequirementType.
ScalarType The scalar type for the calculation. par The FERequirementType object specifying the requirements for the calculation. K The matrix to store the calculated result.
auto Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateScalarImpl(const FERequirementType &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const -> ScalarType
void Ikarus::NonLinearElastic< PreFE, FE, PRE >::calculateVectorImpl(const FERequirementType &par, typename Traits::template VectorType< ScalarType > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
static consteval bool Ikarus::NonLinearElastic< PreFE, FE, PRE >::canProvideResultType()
const auto & Ikarus::NonLinearElastic< PreFE, FE, PRE >::underlying() const
auto & Ikarus::NonLinearElastic< PreFE, FE, PRE >::underlying()