Ikarus::DefaultMembraneStrain
static auto Ikarus::DefaultMembraneStrain::value(const Dune::FieldVector< double, 2 > &gpPos, const GEO &geo, const auto &uFunction) -> Eigen::Vector3< typename std::remove_cvref_t< decltype(uFunction)>::ctype >
Compute the strain vector at a given integration point.
gpPos The position of the integration point. geo The geometry object providing the transposed Jacobian. uFunction The function representing the displacement field. GEO The type of the geometry object. The strain vector at the given integration point.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::computeMaterialAndStrains.
static auto Ikarus::DefaultMembraneStrain::derivative(const Dune::FieldVector< double, 2 > &gpPos, const Eigen::Matrix< ST, 2, 3 > &jcur, const auto &dNAtGp, const GEO &geo, const auto &uFunction, const auto &localBasis, const int node)
Compute the strain-displacement matrix for a given node and integration point.
gpPos The position of the integration point. jcur The Jacobian matrix. dNAtGp The derivative of the shape functions at the integration point. geo The geometry object of the finite element. uFunction The function representing the displacement field. localBasis The local basis object. node The FE node index. GEO The type of the geometry object. ST The scalar type for the matrix elements. The strain-displacement matrix for the given node and integration point.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl, Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateVectorImpl.
static auto Ikarus::DefaultMembraneStrain::secondDerivative(const Dune::FieldVector< double, 2 > &gpPos, const auto &dNAtGp, const GEO &geo, const auto &uFunction, const auto &localBasis, const Eigen::Vector3< ST > &S, int I, int J)
Compute the second derivative of the membrane strain for a given node pair and integration point.
This function computes the geometric tangent stiffness for a given node pair at a given integration point. gpPos The position of the integration point. dNAtGp The derivative of the shape functions at the integration point. geo The geometry object. uFunction The function representing the displacement field. localBasis The local basis object. S The strain vector. I The index of the first node. J The index of the second node. GEO The type of the geometry object. ST The scalar type for the matrix elements. The second derivative of the membrane strain.
Referenced by Ikarus::KirchhoffLoveShell< PreFE, FE >::calculateMatrixImpl.