Ikarus::Truss
using Ikarus::Truss< PreFE, FE >::Traits = PreFE::Traits
using Ikarus::Truss< PreFE, FE >::BasisHandler = typename Traits::BasisHandler
using Ikarus::Truss< PreFE, FE >::FlatBasis = typename Traits::FlatBasis
using Ikarus::Truss< PreFE, FE >::Requirement = FERequirementsFactory<FESolutions::displacement, FEParameter::loadfactor, Traits::useEigenRef>::type
using Ikarus::Truss< PreFE, FE >::LocalView = typename Traits::LocalView
using Ikarus::Truss< PreFE, FE >::Geometry = typename Traits::Geometry
using Ikarus::Truss< PreFE, FE >::GridView = typename Traits::GridView
using Ikarus::Truss< PreFE, FE >::Element = typename Traits::Element
using Ikarus::Truss< PreFE, FE >::Pre = TrussPre
using Ikarus::ResultTypeBase< ResultTypes >::SupportedResultTypes = std::tuple<decltype(makeRT<ResultTypes>())...>
constexpr int Ikarus::Truss< PreFE, FE >::myDim
constexpr int Ikarus::Truss< PreFE, FE >::worldDim
Referenced by Ikarus::Truss< PreFE, FE >::computeStrain.
double Ikarus::Truss< PreFE, FE >::E
double Ikarus::Truss< PreFE, FE >::A
Ikarus::Truss< PreFE, FE >::Truss(const Pre &pre)
Constructor for the Truss class.
pre The pre fe
auto Ikarus::Truss< PreFE, FE >::displacement(const Requirement &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const
Gets the displacement for the given Requirement and optional displacement vector.
ST The scalar type for the displacement vector. par The Requirement object. dx Optional displacement vector. The local displacement vector of the type Dune::BlockVector<Dune::RealTuple<ST, worldDim>>
Referenced by Ikarus::Truss< PreFE, FE >::computeStrain.
KinematicVariables< ST > Ikarus::Truss< PreFE, FE >::computeStrain(const Requirement &par, const std::optional< std::reference_wrapper< const Eigen::VectorX< ST > > > &dx=std::nullopt) const
Gets the strain for the given Requirement and optional displacement vector.
ST The scalar type for the strain. par The Requirement object. dx Optional displacement vector. A tuple containing Green-Lagrange strain, its first and second derivatives w.r.t displacements and the length of the undeformed and deformed geometry.
Referenced by Ikarus::Truss< PreFE, FE >::calculateAtImpl, Ikarus::Truss< PreFE, FE >::calculateMatrixImpl, Ikarus::Truss< PreFE, FE >::calculateScalarImpl, Ikarus::Truss< PreFE, FE >::calculateVectorImpl.
auto Ikarus::Truss< PreFE, FE >::calculateAtImpl(const Requirement &req, const Dune::FieldVector< double, Traits::mydim > &local, Dune::PriorityTag< 0 >) const
Calculates a requested result at a specific local position.
req The Requirement object holding the global solution. local Local position vector. RT The requested result type calculated result RT The type representing the requested result.
const auto & Ikarus::Truss< PreFE, FE >::underlying() const
auto & Ikarus::Truss< PreFE, FE >::underlying()
void Ikarus::Truss< PreFE, FE >::calculateMatrixImpl(const Requirement &par, const MatrixAffordance &affordance, typename Traits::template MatrixType<> K, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
auto Ikarus::Truss< PreFE, FE >::calculateScalarImpl(const Requirement &par, ScalarAffordance affordance, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const -> ScalarType
void Ikarus::Truss< PreFE, FE >::calculateVectorImpl(const Requirement &par, VectorAffordance affordance, typename Traits::template VectorType< ScalarType > force, const std::optional< std::reference_wrapper< const Eigen::VectorX< ScalarType > > > &dx=std::nullopt) const
static consteval bool Ikarus::ResultTypeBase< ResultTypes >::supportsResultType()
Returns whether a ResultType is provided by the element.
RT requested ResultType