Ikarus::Materials::Material
using Ikarus::Materials::Material< MI >::MaterialImpl = MI
Type of material implementation.
constexpr bool Ikarus::Materials::Material< MI >::isReduced
Static constant for determining if the material has vanishing stress or strain components (is reduced).
constexpr double Ikarus::Materials::Material< MI >::derivativeFactor
This factor denotes the differences between the returned stresses and moduli and the passed strain.
For neoHooke the inserted quantity is $C$ the Green-Lagrangian strain tensor, the function relation between the energy and the stresses is $S = 1 \dfrac{\partial\psi(E)}{\partial E}$. This factor is the pre factor, which is the difference to the actual derivative, which is written here
constexpr const MaterialImpl & Ikarus::Materials::Material< MI >::impl() const
Const accessor to the underlying material (CRTP).
Const reference to the underlying material.
Referenced by Ikarus::Materials::Material< MI >::materialParameters, Ikarus::Materials::Material< MI >::rebind, Ikarus::Materials::Material< MI >::storedEnergy.
constexpr MaterialImpl & Ikarus::Materials::Material< MI >::impl()
Accessor to the underlying material (CRTP).
Reference to the underlying material.
auto Ikarus::Materials::Material< MI >::materialParameters() const
Returns the material parameters stored in the implemented material.
Material parameter.
auto Ikarus::Materials::Material< MI >::storedEnergy(const Eigen::MatrixBase< Derived > &Eraw) const
Return the stored potential energy of the material.
This function return the free Helmholtz energy of the material tag Strain tag indicating which strain tensor components are passed. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Scalar return of stored energy.
auto Ikarus::Materials::Material< MI >::stresses(const Eigen::MatrixBase< Derived > &Eraw) const
Get the stresses of the material.
tag Strain tag indicating which strain tensor components are passed. voigt Boolean indicating whether to return Voigt-shaped result. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Vectorial or Matrix return of stresses.
auto Ikarus::Materials::Material< MI >::tangentModuli(const Eigen::MatrixBase< Derived > &Eraw) const
Get the tangentModuli of the material.
tag Strain tag indicating which strain tensor components are passed. voigt Boolean indicating whether to return Voigt-shaped result. Derived The underlying Eigen type. Eraw The strain tensor components passed in Voigt notation or matrix notation. Tangent moduli in Voigt notation or as fourth-order tensor.
auto Ikarus::Materials::Material< MI >::rebind() const
Rebind material to a different scalar type.
Useful for using automatic differentiation. STO The scalar type to rebind to. Rebound material.
static constexpr std::string Ikarus::Materials::Material< MI >::name()
Get the name of the implemented material.
Name of the material.
auto Ikarus::Materials::Material< MI >::stressesMaybeTransformInputToVoigt(const Eigen::MatrixBase< Derived > &E) const
auto Ikarus::Materials::Material< MI >::tangentModuliMaybeTransformInputToVoigt(const Eigen::MatrixBase< Derived > &E) const