Ikarus::LinearSolverTemplate
using Ikarus::LinearSolverTemplate< ST >::ScalarType = ST
using Ikarus::LinearSolverTemplate< ST >::SparseMatrixType = Eigen::SparseMatrix<ScalarType>
using Ikarus::LinearSolverTemplate< ST >::DenseMatrixType = Eigen::MatrixX<ScalarType>
std::unique_ptr<SolverBase> Ikarus::LinearSolverTemplate< ST >::solverimpl_
SolverTypeTag Ikarus::LinearSolverTemplate< ST >::solverTypeTag_
Ikarus::LinearSolverTemplate< ST >::LinearSolverTemplate()=default
Ikarus::LinearSolverTemplate< ST >::LinearSolverTemplate(const SolverTypeTag &solverTypeTag)
Constructor for LinearSolverTemplate.
solverTypeTag The solver type tag representing the type of the linear solver.
Ikarus::LinearSolverTemplate< ST >::~LinearSolverTemplate()=default
Destructor for LinearSolverTemplate.
LinearSolverTemplate & Ikarus::LinearSolverTemplate< ST >::operator=(const LinearSolverTemplate &other)
Copy assignment operator.
other The LinearSolverTemplate to copy. A reference to the assigned LinearSolverTemplate.
Ikarus::LinearSolverTemplate< ST >::LinearSolverTemplate(const LinearSolverTemplate &other)
Copy constructor.
other The LinearSolverTemplate to copy.
Referenced by Ikarus::LinearSolverTemplate< ST >::LinearSolverTemplate.
Ikarus::LinearSolverTemplate< ST >::LinearSolverTemplate(LinearSolverTemplate &&other) noexcept=default
Move constructor.
other The LinearSolverTemplate to move.
LinearSolverTemplate & Ikarus::LinearSolverTemplate< ST >::operator=(LinearSolverTemplate &&other) noexcept=default
Move assignment operator.
other The LinearSolverTemplate to move. A reference to the assigned LinearSolverTemplate.
LinearSolverTemplate & Ikarus::LinearSolverTemplate< ST >::compute(const MatrixType &A)
Compute the factorization of the matrix.
MatrixType The type of the matrix (DenseMatrixType or SparseMatrixType). A The matrix for factorization. A reference to the LinearSolverTemplate.
Referenced by Ikarus::LinearSolverTemplate< ST >::compute, Ikarus::LinearSolverTemplate< ST >::operator=.
void Ikarus::LinearSolverTemplate< ST >::analyzePattern(const MatrixType &A)
Analyze the pattern of the matrix.
MatrixType The type of the matrix (DenseMatrixType or SparseMatrixType). A The matrix for pattern analysis.
Referenced by Ikarus::LinearSolverTemplate< ST >::operator=.
void Ikarus::LinearSolverTemplate< ST >::factorize(const MatrixType &A)
Factorize the matrix.
MatrixType The type of the matrix (DenseMatrixType or SparseMatrixType). A The matrix for factorization.
Referenced by Ikarus::LinearSolverTemplate< ST >::operator=.
void Ikarus::LinearSolverTemplate< ST >::solve(Eigen::VectorX< ScalarType > &x, const Eigen::VectorX< ScalarType > &b)
Solve the linear system for a vector.
x The solution vector. b The right-hand side vector.
Referenced by Ikarus::LinearSolverTemplate< ST >::operator=.
void Ikarus::LinearSolverTemplate< ST >::solve(Eigen::MatrixX3< ScalarType > &x, const Eigen::MatrixX3< ScalarType > &b)
Solve the linear system for a n times 3 matrix.
x The solution matrix. b The right-hand side matrix.
void Ikarus::LinearSolverTemplate< ST >::solve(Eigen::MatrixX2< ScalarType > &x, const Eigen::MatrixX2< ScalarType > &b)
Solve the linear system for a n times 2 matrix.
x The solution matrix. b The right-hand side matrix.
void Ikarus::LinearSolverTemplate< ST >::solve(Eigen::MatrixX< ScalarType > &x, const Eigen::MatrixX< ScalarType > &b)
Solve the linear system for a n times n matrix.
x The solution matrix. b The right-hand side matrix.
void swap(LinearSolverTemplate &lhs, LinearSolverTemplate &rhs) noexcept
Referenced by Ikarus::LinearSolverTemplate< ST >::operator=.