Ikarus::DirichletValues
using Ikarus::DirichletValues< B, FC >::Basis = std::remove_cvref_t<B>
using Ikarus::DirichletValues< B, FC >::FlagsType = FC
using Ikarus::DirichletValues< B, FC >::BackendType = decltype(Dune::Functions::istlVectorBackend(std::declval<FlagsType&>()))
using Ikarus::DirichletValues< B, FC >::SizeType = typename DeriveSizeType<FlagsType>::SizeType
constexpr int Ikarus::DirichletValues< B, FC >::worldDimension
Eigen::VectorXd Ikarus::DirichletValues< B, FC >::inhomogeneousBoundaryVectorDummy_
Basis Ikarus::DirichletValues< B, FC >::basis_
FlagsType Ikarus::DirichletValues< B, FC >::dirichletFlags_
BackendType Ikarus::DirichletValues< B, FC >::dirichletFlagsBackend_
std::vector<DirichletFunctions> Ikarus::DirichletValues< B, FC >::dirichletFunctions_
Ikarus::DirichletValues< B, FC >::DirichletValues(const B &basis)
void Ikarus::DirichletValues< B, FC >::fixBoundaryDOFs(F &&f, TreePath &&treePath={})
Function to fix (set boolean values to true or false) degrees of freedom on the boundary.
This function takes a callback function, which will be called with the boolean vector of fixed boundary degrees of freedom and the usual arguments of Dune::Functions::forEachBoundaryDOF. f A callback function treePath An optional argument specifying a tree path to a subspacebasis, e.g. Dune::Indices::_0
void Ikarus::DirichletValues< B, FC >::fixDOFs(F &&f)
Function to fix (set boolean values to true or false) degrees of freedom.
This function takes a callback function, which will be called with the stored function space basis and the boolean vector of fixed boundary degrees of freedom. f A callback function
Referenced by Ikarus::Python::registerDirichletValues.
void Ikarus::DirichletValues< B, FC >::setSingleDOF(const MultiIndex i, bool flag)
Fixes and unfixes (set boolean value to true or false) a specific degree of freedom.
i An index indicating the DOF number to be fixed flag Boolean indicating whether the DOF should fixed or not
Referenced by Ikarus::Python::registerDirichletValues.
void Ikarus::DirichletValues< B, FC >::setSingleDOF(std::size_t i, bool flag)
Fixes or unfixes (set boolean value to true or false) a specific degree of freedom.
i An index indicating the DOF number to be fixed flag Boolean indicating whether the DOF should fixed or not
void Ikarus::DirichletValues< B, FC >::reset()
Resets all degrees of freedom.
Referenced by Ikarus::Python::registerDirichletValues.
const auto & Ikarus::DirichletValues< B, FC >::basis() const
bool Ikarus::DirichletValues< B, FC >::isConstrained(const MultiIndex &multiIndex) const
Referenced by Ikarus::Python::registerDirichletValues.
bool Ikarus::DirichletValues< B, FC >::isConstrained(std::size_t i) const
auto Ikarus::DirichletValues< B, FC >::fixedDOFsize() const
Referenced by Ikarus::Python::registerDirichletValues.
auto Ikarus::DirichletValues< B, FC >::size() const
Referenced by Ikarus::Python::registerDirichletValues.
auto & Ikarus::DirichletValues< B, FC >::container() const
Referenced by Ikarus::Python::registerDirichletValues.
void Ikarus::DirichletValues< B, FC >::storeInhomogeneousBoundaryCondition(F &&f)
Function to insert a function for inhomogeneous Dirichlet boundary conditions.
This function takes a callback function, which will be called with the current coordinate vector and the scalar load factor. It creates internally the first derivative of the passed function and stores them simultaneously. f A callback function
void Ikarus::DirichletValues< B, FC >::evaluateInhomogeneousBoundaryCondition(Eigen::VectorXd &xIh, const double &lambda)
Function to evaluate all stored inhomogeneous Dirichlet boundary functions.
This function evaluates all stored inhomogeneous Dirichlet boundary functions at all positions where the corresponding degrees of freedom are true. xIh The vector where the interpolated result should be stored lambda The load factor
void Ikarus::DirichletValues< B, FC >::evaluateInhomogeneousBoundaryConditionDerivative(Eigen::VectorXd &xIh, const double &lambda)
Function to evaluate all stored inhomogeneous Dirichlet boundary derivative functions.
This function evaluates all stored inhomogeneous Dirichlet boundary derivative functions at all positions where the corresponding degrees of freedom are true. xIh The vector where the interpolated result should be stored lambda The load factor